### ISSUE TITLE
Artifact.data should be lazy

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#10]
Currently when instantiating an `Artifact` from a tar file, the artifact's data is loaded into memory and stored at the `data` property. The `data` property should be lazy such that the data is only loaded when `.data` is first accessed.

Question: should this always load a new instance of data, or cache the result? This depends on how `Artifact` is expected to be interacted with, which is unclear to me right now.

**Comment by antgonza** [comment]
Currently in Qiita an artifact is simply a file location or entry in the DB with a format type. For example, an artifact can be raw fastq files (raw_forward/reverse/barcode_fastq) or a biom. However, you can only apply split_libraries to raw formats and beta diversity to bioms.

**Comment by ebolyen** [comment]
@antgonza, our artifacts aren't too different, but this is in regards to the actual `object` and it's API.

**Comment by antgonza** [comment]
OK, thanks. Then I think everything, wherever possible, should be lazy. I'm concern about know issues like trying to load all sequences.

**Comment by wasade** [comment]
Agree that lazy is ideal

**Comment by jairideout** [comment]
`Artifact` is now lazy and views of the data can be created using `Artifact.view`.
