### ISSUE TITLE
formalize communication channels with developers

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#102]
at our meeting in Austin we discussed using slack for developer conversation and blog.qiime.org for announcements about backward incompatible changes, etc (and then we'd tweet the individual posts).

- [x] create slack room
- [x] document this in a wiki page

**Comment by wasade** [comment]
:+1:

Will biocore maintain a presence on gitter

**Comment by gregcaporaso** [comment]
We might want to distinguish between the developer slack team that we set up now (qiime2-developers.slack.com?) and an eventual user slack room that we don't set up now (qiime2-users.slack.com?). What do you guys think?

**Comment by ebolyen** [comment]
Wouldn't slack just have different rooms? (I have no idea how it works)

**Comment by wasade** [comment]
Great!

What about:

- micro.slack.com
- microbiome.slack.com
- all-the-ome.slack.com
- the-crobe.slack.com
- pycrobe.slack.com
- q2.slack.com
- q.slack.com
- qii.slack.com

...just some brain dump thoughts

**Comment by gregcaporaso** [comment]
Oh, if that's the case then definitely qiime2.slack.com.

**Comment by wasade** [comment]
could just be different ACL channels though under the same team

**Comment by thermokarst** [comment]
Channels under the team makes the most sense. The team is the unifying umbrella that everything falls under.

**Comment by gregcaporaso** [comment]
ok, i like qiime2 for this one then, rather than one of the more general ideas.

**Comment by ebolyen** [comment]
>  all-the-ome.slack.com

definitely this

and more seriously, :+1:  for `qiime2.slack.com`

**Comment by wasade** [comment]
:) ya, same

**Comment by gregcaporaso** [comment]
Great, let's go with qiime2.slack.com. Thanks @thermokarst!
