### ISSUE TITLE
support user-configured temporary directory

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#12]
Similar to QIIME 1's `temp_dir` config option, QIIME 2 should support a config file/directory where users can specify a temporary directory. `ArtifactDataWriter` should respect this temp dir in its call to `tempfile.TemporaryDirectory`.

**Comment by gregcaporaso** [comment]
The first step here will be to create ``qiime.sdk.config.gettempdir()`` which will return the result of ``tempfile.gettempdir()``. Then, make sure this is always used in qiime and the interfaces. Finally, allow the return value of ``qiime.sdk.config.gettempdir()`` to be user-configurable, using Python's ``configparser``. 

We also want a ``qiime.sdk.config.mkdtemp()`` and a class ``qiime.sdk.config. TemporaryDirectory``, both of which override the corresponding function/object in Python's ``tempfile`` and override prefix to prepend ``q2-`` and dir to always be the result of calling ``qiime.sdk.config.gettempdir()``. Then, update the framework, interfaces and plugins to replace calls to the tempfile versions of these with calls to the QIIME versions of these.

**Comment by jairideout** [comment]
Currently the framework uses the default (platform-specific) temporary directory returned by `tempfile.gettempdir()`. If this temp directory needs to change, there are several ways to override it. See [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) and [here](https://docs.python.org/3/library/tempfile.html#tempfile.tempdir) for details. Searching the QIIME 1 forum and issue tracker will also yield many examples of how to do this. This is obviously just a workaround until the framework supports configurable temporary directories.

**Comment by wasade** [comment]
There is a more general way to do this as well, which is to set the environment variable `TMPDIR`, which Python will also honor. What's nice about this is it should also inform any wrapped processes as well about what directory to use.

One strategy that I'm currently undertaking when driving things via bash scripts is to do:

```bash
#!/bin/bash
set -e

source activate q2-2017.2

export TMPDIR=<SYSTEM-SPECIFIC-PATH>  
tmp=$(mktemp -d --tmpdir)

# update TMPDIR to the newly created dir so that any downstream
# processes knows of its existence and hopefully uses it  
export TMPDIR=$tmp  

# from http://stackoverflow.com/a/2130323
# registers a bash function to run at exit from the script
function cleanup {
  echo "Removing $tmp"
  rm  -r $tmp
  unset TMPDIR
}
trap cleanup EXIT

# do stuff
```

**Comment by jairideout** [comment]
Closing in favor of #232.
