### ISSUE TITLE
The comments regarding license need updating

### ISSUE THREAD

**Issue by GavinHuttley** [qiime2/qiime2#124]
The code indicates, in comments, that

```
# The full license is in the file COPYING.txt, distributed with this software.
```

That file is not present in the repo. I presume it is meant to be changed to "LICENSE".

**Comment by thermokarst** [comment]
Thanks @GavinHuttley! This just came up in a discussion on Friday and we missed capturing it in a formal to-do --- great timing on your end to open up an issue! We would certainly welcome a PR with updated headers, otherwise stay tuned and we will keep you posted. Thanks!

**Comment by thermokarst** [comment]
And yes, your are right, this should indicate `LICENSE` instead of `COPYING.txt`.
