### ISSUE TITLE
DirectoryFormat: Improve API when constructing

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#127]
**Current Behavior**
Right now it is _very_ tedious to construct a complex `DirectoryFormat`. It involves constructing each of it's component files and then using `write_data` to do an identity transformation into the format. This is a waste of everyone's time. Instead there should probably be some API that constructs on already bound file in the directory.

**Proposed Behavior**
Options include:

``` python
file = dirfmt.file(...)
```

Also discussed was something like:

``` python
dirfmt.file.write_line("Some test")
```

Though that may contradict a statement like the above.

**Comments**
In any case this needs to be dramatically improved soon.

**Comment by Oddant1** [comment]
@ebolyen reopen if you think this is really important, but seems to have fallen by the wayside
