### ISSUE TITLE
DirectoryFormat: expose capture groups from the pathspec

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#129]
**Comments**
This would cut down on duplicated parsing allowing the directory format to basically define what would be yielded by `iter_views` (other than the view). 

**Questions**
This depends a little bit on #128 as it is usually the consumer of what is yielded. Is it possible to make that dependency transparent? Is that even a good thing to do?

**References**
#128

**Comment by Oddant1** [comment]
@ebolyen reopen if you think this is really important, but seems to have fallen by the wayside
