### ISSUE TITLE
ArtifactDataWriter should set appropriate file metadata

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#14]
`ArtifactDataWriter` should set appropriate file metadata/attributes when saving files to the tar archive (e.g., owner, permissions, etc.). I'm not sure exactly what those should be; see [TarInfo](https://docs.python.org/2/library/tarfile.html#tarinfo-objects) for the possible file attributes that can be set.

**Comment by ebolyen** [comment]
Perhaps a pseudo `qiime` user with `777` as permissions? We definitely don't want to leak system information in these artifacts.

**Comment by wasade** [comment]
What about 666 for files and 777 for directories? 777 makes sense for
executable files.

I can see benefit in 444 for some files...

**Comment by antgonza** [comment]
I'm not 100% sure we need to worry about this in qiime2. Should this be handled by the tools using qiime2?

**Comment by jairideout** [comment]
This is QIIME 2's responsibility because it defines and implements the .qtf format, and we don't want to leak system information in artifacts. Note that we're talking about file permissions for files that are added to the tar archive.

**Comment by jairideout** [comment]
Closing as new `.qza`/`.qzv` archive format is ZIP64-based which doesn't have file metadata like this to set.
