### ISSUE TITLE
QIIME logger

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#141]
**Improvement Description**
qiime.core.logger (or somewhere else that makes more sense) should be available for logging to. Eventually we should have debug and info level log statements throughout the framework (e.g. transformers transforming, plugins registering, etc.). This can be exposed through API pretty easily, and would also allow for q2cli to have a --verbose {0,1,2,3} type flag. The verbosity level could also be set in a qiime config, whenever that comes along.

**Questions**
1. Where should this code live? I have proposed qiime.core.logger, but other locations might work, too.
2. If not applicable, please delete this section.

**Comment by Oddant1** [comment]
@ebolyen do you think we'll ever want to actually do this? It would be quite a bit of work at this point.
