### ISSUE TITLE
speed up framework imports

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#151]
**Improvement Description**
A top-level import of the framework (`import qiime`) takes ~0.5 second. It would be great to speed this up, especially for command-line applications and interactive use. Note that I tested this with an installation of the framework that's not in "development" mode (`pip install -e`) as that slows imports down a lot and doesn't represent the speed a user would encounter.

**Comment by wasade** [comment]
Import burden is one of the main sources of sluggish cli response. Agree
this would be awesome to improve. Some may come from click as well -- I've
never benched a naive click hello word

**Comment by jairideout** [comment]
Yes some import time comes from Click. Note that the framework's import time of half a second is independent of Click (I tested `import qiime` in an IPython session).

**Comment by wasade** [comment]
Ah, okay, thank you. I did some reading on this a bit ago and the basic
suggestion was to defer imports. One thing skbio and qiime do heavily is
bring in a lot into their namespaces from just a `import qiime` which
triggers a imports into the hierarchy into the submodules etc. It might be
interesting to monitor `lsof` or `strace` during an import...

**Comment by jairideout** [comment]
Thanks for the details about deferring imports. I wonder how numpy gets away with this? Their import times are pretty snappy and they bring everything under the `numpy` top-level package.

**Comment by Oddant1** [comment]
At this point concerns have been raised about potentially reducing the overhead of QIIME 2 in Python period. We do not currently have the resources to address it, but it is broadly on our radar.
