### ISSUE TITLE
qiime.plugin utility function for making system calls

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#153]
This will allow plugins to make system calls in the same way, which will facilitate error handling. I started on this in gregcaporaso/q2-dada2#1.

**Comment by wasade** [comment]
Just a note, we may want to allow passing in a stream for verbose output so
that control over the fd receiving the output can be managed higher in the
stack

**Comment by gregcaporaso** [comment]
We're going to close this one open now as the different plugins require some different handling, so it's not clear that we're ready for a general purpose function. We might revisit in the future, once we have a few more plugins that are making system calls.
