### ISSUE TITLE
Sample files for Qiime2

### ISSUE THREAD

**Issue by jjsimz** [qiime2/qiime2#162]
Hi all,
I am new to Qiime and Qiime2, pardon me if the solution is obvious.

Is there any way I can find test data for:
sample_metadata
otu_metadata
unrarefied_biom

so that I can test-run Qiime 2

-Choon

**Comment by thermokarst** [comment]
Hi @jjsimz, we have new documentation and QIIME 2 releases coming towards the end of this week. This should include a lot of exciting new features and tutorial datasets. We will follow up with you as soon as we have something to share!

**Comment by jjsimz** [comment]
Hi @thermokarst, this definitely sounds exciting!

**Comment by gregcaporaso** [comment]
Hi @jjsimz, The releases are now live, and there is new tutorial data available at 2.qiime.org (see the *Tutorials* section). You can see the release notes [here](https://github.com/qiime2/qiime2/releases/tag/2.0.5). Thanks for your interest in QIIME 2!
