### ISSUE TITLE
Typo at title for "plot_taxa_summary.py": Home » QIIME File Formats » QIIME Scripts

### ISSUE THREAD

**Issue by lakhujanivijay** [qiime2/qiime2#163]
Script: `plot_taxa_summary.py`

Location/Link: [http://qiime.org/scripts/plot_taxa_summary.html]()

Typo (in bold): plot_taxa_summary.py – Make **taxaonomy** summary charts based on taxonomy assignment

![typo](https://cloud.githubusercontent.com/assets/9314053/19141220/0b3116ec-8bb1-11e6-8f3e-1a0b435b76b1.png)

**Comment by jairideout** [comment]
Thanks for reporting this @lakhujanivijay! This repository and issue tracker are for QIIME 2, which is a complete redesign/rewrite of QIIME 1. Can you please post the issue on the [QIIME 1 issue tracker](https://github.com/biocore/qiime/issues) instead?
