### ISSUE TITLE
Q2.0.5 Installation issue on linux cluster [SOLVED]

### ISSUE THREAD

**Issue by nbokulich** [qiime2/qiime2#169]
This issue has been solved, but I am posting the solution in case others encounter this during installation.

When installing on a linux HPC following the 2.0.5 release [installation instructions](http://2.qiime.org/docs/install.html), `qiime2` and plugins would install, but plugins were not detectable, e.g., `qiime info` would not list any installed plugins. When `qiime2` would cache the deployment, I would get the following exception:

`ImportError: /home/nab336/.conda/envs/qiime2-05/lib/python3.5/site-packages/PyQt4/QtCore.so: undefined symbol: _ZN7QLocale14scriptToStringENS_6ScriptE`

@thermokarst solved this issue, as a related problem with [this issue](https://github.com/qiime2/qiime2/issues/73). After installing `matplotlib`, set the backend parameter with:
`echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc`

Now `qiime info` detects all plugins and, e.g., `qiime diversity --help` works as expected. 

Thanks @thermokarst !

**Comment by jairideout** [comment]
Thanks @nbokulich! This unfortunately is a conda matplotlib package issue. Maybe to "resolve" this issue we can add a troubleshooting / common problems section to the install docs with these sorts of details as they come up?

**Comment by gregcaporaso** [comment]
I like the idea of a troubleshooting section on the install document.

Thanks @nbokulich and @thermokarst!

**Comment by thermokarst** [comment]
Closing this. We don't have a troubleshooting section on the docs (but there is an [issue](https://github.com/qiime2/docs/issues/61)). For this specific problem, we do have a relevant [topic on the forum](https://forum.qiime2.org/t/qiime2-plugins-not-found-though-they-are-installed/112/2).
