### ISSUE TITLE
Some QIIME2 plugins will fail without feature IDs, should return more informative error message

### ISSUE THREAD

**Issue by johnchase** [qiime2/qiime2#173]
**Current Behavior**
Currently

`phylogeny.methods.fasttree()`  
will fail if the sequences passed do not have IDs associated with them. In the example below `feat_table` is a `pd.DataFrame` where the columns are the features and the rows samples. column names are the sequences themselves

``` python
seqs = (skbio.DNA(e) for e in feat_table.columns)
dna_iter = DNAIterator(seqs)
a = qiime.Artifact.import_data(FeatureData[Sequence], dna_iter)
aligned_seqs = alignment.methods.mafft(a)
filtered_aligned_seqs = alignment.methods.mask(aligned_seqs.alignment)
tree = phylogeny.methods.fasttree(filtered_aligned_seqs.masked_alignment)

...
CalledProcessError: Command '['FastTree', '-nt', '/tmp/qiime2-archive-btn74mqp/2a834841-54b7-4d1e-9c75-23181d4ad7db/data/aligned-dna-sequences.fasta']' returned non-zero exit status 1
```

**Proposed Behavior
If this should in fact fail a more useful error message should be returned letting the user know that IDs are required. I would argue, however, that sequences should not need IDs as they will always be unique, and the solutions for dealing with this are not ideal.

The first solution to get around the error is either to use the sequences as the IDs for the sequences:  
`seqs = (skbio.DNA(e, metadata={'id':e}) for e in feat_table.columns)`
This is a good solution though it does mean redundant information is being stored

Another solution is use the the sequence map file/object generated upstream by qiime2 which will contain either the sequence as it's own ID or the sequence's md5sum as it's ID. This is not ideal because 1. It assumes such a file exists and 2. It means having to maintain two files (or in our case two tables in a database) because we are often analyzing multiple runs it is easier and safer to only maintain the sequences in one location.

Perhaps if IDs are not present the default could be to use the sequences as the IDs?

**Comments**
I'm not sure if it is better to post this here or on the specific plugin I am having an issue with, however I imagine this issue will be present across many plugins. I can port this issue to another repo if needed.

**References**
This issue is relevant in context of https://github.com/benjjneb/q2-dada2/issues/4.

**Comment by Oddant1** [comment]
I THINK we kinda do this now right? Because we would now error saying the metadata needs to have an `id` column or whatever?
