### ISSUE TITLE
exclude parameter to Properties should be less restrictive

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#177]
**Comments**
In the context of https://github.com/qiime2/q2-diversity/issues/35 we discussed allowing the `exclude` parameter to `Properties` to match types that don't have any information about the specified `Property`. This potentially creates a problem because a missing `Property` could either mean that the artifact does or doesn't have the feature indicated by the `Property` (for example, it might have that feature, but predate the existence of the `Property`).

**References**
1. https://github.com/qiime2/q2-diversity/issues/35
2. See https://github.com/qiime2/q2-diversity/issues/35 for use cases.

**Comment by Oddant1** [comment]
@gregcaporaso I don't think I've ever seen this come up anywhere (for all I know it isn't an issue anymore) reopen if you think it still needs something to happen
