### ISSUE TITLE
Visualization Indices

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#178]
**Improvement Description**
A `Visualization` object currently has `get_index_paths`, which is super convenient. It would be really cool if that info was encoded somewhere in a viz archive, so that tools that need to be aware of multiple indices can read from an authoritative digest, rather than manually traversing the data dir (which is how view.qiime2.org works right now). This could also allow for specifying the 'default' index (like index.html, while there might also be an index.docx (gross!) available in the archive as well).

**Comment by Oddant1** [comment]
@ebolyen This is probably not relevant given that it has been open since 2016, but if you think it's relevant to the impending view rewrite in some way. . . ?
