### ISSUE TITLE
verify Type.__ne__ behavior is correct

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#18]
Should `Type.__ne__` be implemented as `(not self < other) and (not self > other)`?

**Comment by ebolyen** [comment]
In other words, should `ne` simply mean not `eq`, or is it a stronger statement? Such as having no hierarchical relationship between compared types?

**Comment by ebolyen** [comment]
Now it is the inverse of `__eq__` which is only deep (but not semantic!) equality. `__eq__` is not semantic equality in order to make `__hash__` possible to reason about.
