### ISSUE TITLE
Plugin entry-point key should be the machine id of a plugin

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#19]
**Improvement Description**
while the `name` argument provided to the `Plugin` constructor should be the human-readable name.

**Comment by antgonza** [comment]
Could you expand on what you mean with entry-point key?

**Comment by jairideout** [comment]
https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins

**Comment by antgonza** [comment]
Thanks.

**Comment by ebolyen** [comment]
Sorry, should have included the link.

**Comment by gregcaporaso** [comment]
@ebolyen, reopen if you think this is still relevant.
