### ISSUE TITLE
standard error from external applications does not display in jupyter notebook

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#190]
**Improvement Description**
The stderr that should be generated by the ``mafft`` and ``fasttree`` calls is going to the terminal where I executed ``jupyter notebook``, where stderr typically displays in the notebook (see other commands in the notebook). 

**References**
[This notebook](https://gist.github.com/gregcaporaso/681c1c20ea834edcf2cb834b206c22ce) illustrates the problem.

**Comment by jairideout** [comment]
Possibly related to #219.

**Comment by Oddant1** [comment]
Tied to #219 I don't think this is happening anymore? I'm pretty sure I've run a lot of notebooks that have had stdio and stderr from external sources that showed up in the notebooks. Regardless this clearly wasn't prioritized.
