### ISSUE TITLE
Indices in QIIME 2

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#192]
**Comments**
It may be the case that semantic types posses the notion of an "index" meaning that our archive format could store indices. This has the potential to allow the framework to agnostically manage artifacts and perform the following operations:

 - Generic filtering (without the need for a TypeMap, or similar machinery)
 - Semantic Predicates that define inter-artifact index relations:
    - Matching index
    - Intersection
    - Union
   - etc...
- Generic input-splitting (via chunking an index, and filtering) in the context of map-reduce
- Validating that a given metadata file makes sense in the context of a given artifact
- (and probably more)

**Comment by thermokarst** [comment]
For additional consideration --- there is some potential impact here on our understanding of visualizations. Semantic type indices + filtering could be a major driver in our design of a cross-filtering aware viz platform.

**Comment by Oddant1** [comment]
@ebolyen it seems like we've basically addressed this to the degree we care to, but feel free to reopen if I'm wrong.
