### ISSUE TITLE
Suggestion: Throw input errors when em-dash detected in input

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/qiime2#195]
I'm not sure if this is the right place for this suggestion, so please help me find the best location.

New linux users periodically end up with the [em-dash in their commands](https://groups.google.com/forum/#!topic/qiime-forum/U9X2C_lsExo), which breaks the script in a opaque way.

Would it be possible to throw an explicit and constructive error or warning any time an em-dash is detected in the input?

**Comment by ebolyen** [comment]
Hey @colinbrislawn! This is a good idea, could you repost this to the `q2cli` [issue tracker](https://github.com/qiime2/q2cli/issues)? Thanks! (This will depend on what we can get `click` to do, but we should discuss that there further).
