### ISSUE TITLE
plugin API support for artifact summary/stats

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#197]
**Improvement Description**
It'd be useful to implement a plugin API to generate summary stats of the artifact's data (on a per-type, per-view basis, or both?). This summary would fit nicely into metadata.yml and could be displayed in operations such as `peek` and q2view.

**References**
Originally posted in https://forum.qiime2.org/t/quickly-get-general-stats-about-artifact/172

**Comment by antgonza** [comment]
Adding another specific use case for this: benchmarking. Currently if you generate 100s of qza/biom files and want to count samples or features for each of them to create a csv file, you need to extract each of the files and then run biom on each of them: this raises the time to do this work and also duplicates the information (more files!). So it will be nice to have the summaries displayed via the peek or the `qiime feature-table summarize` command.

**Comment by gregcaporaso** [comment]
@antgonza, note that if you're doing this on many files, using the [artifact API](https://docs.qiime2.org/2017.4/interfaces/artifact-api) is probably the best way to do this. In Python, you could iterate over all of the qza files and do something like:

```python
table_shapes = []
qzas = # some collection of your qzas
for qza in qzas:
    table = Artifact.load(qza)
    table_shapes.append(table.view(biom.Table).shape)
```

**Comment by antgonza** [comment]
@gregcaporaso, thanks! ... ended up doing some bash scripting.

**Comment by cuttlefishh** [comment]
Following on this, I had some discussions with @antgonza and @thermokarst about adding functionality to preview artifacts. Something like `tabview` (with `less`-style functionality) to preview table objects, or an option to get more of a `biom summarize-table` output (perhaps also with `less`-style functionality). I think this would help users quickly check on output artifacts after running commands. @thermokarst mentioned at least one other user who had expressed interest in a similar idea.

**Comment by Oddant1** [comment]
This seems like it would be nice to have, but I'm closing it for now. @ebolyen, do we care a whole lot about this?
