### ISSUE TITLE
ENH: Robust Format Sniffers

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#201]
**Improvement Description**
Based on recent discussion, it seems useful to make sniffing more robust, including the ability to raise specific errors when a sniffer fails. Also there was some talk around conditional logic within a sniffer ("if this then do this"), to possibly handle more generic directory formats for importing. This would impact end users and plugin developers.

**Comment by Oddant1** [comment]
This doesn't seem like it's going to happen
