### ISSUE TITLE
provide Dockerfile for qiime2

### ISSUE THREAD

**Issue by mes5k** [qiime2/qiime2#207]
There's a docker image for qiime2 available on Docker Hub ([here](https://hub.docker.com/r/qiime2/core/)), but the Dockerfile used to create this image isn't linked.  Could you provide Dockerfile somewhere as source?  I imagine that the code to generate VirtualBox and Amazon images would also be helpful.

**Comment by thermokarst** [comment]
Hi @mes5k, we actually don't build the Docker image using a Dockerfile, but rather through a set of `ansible` playbooks (and then we back the Docker image using `packer`). You can visit the [playbooks](https://github.com/qiime2/playbooks) repo for more info on how this works. The VirtualBox and AWS images are also built this way, and are available in the same repo.

**Comment by mes5k** [comment]
Very interesting - I didn't know you could do that.  Will learn something new today!

**Comment by thermokarst** [comment]
@mes5k - the docs are virtually none for our provisioning stuff right now, so if you run into any problems, feel free to post an issue on the `playbooks` repo, or find one of us on [slack](https://docs.qiime2.org/2.0.6/community/#slack-team-developers)!

**Comment by jcuhpc** [comment]
Looking at the playbooks repo, there is a dockerfile.
