### ISSUE TITLE
Denote input or output when handing artifacts over the API

### ISSUE THREAD

**Issue by wasade** [qiime2/qiime2#217]
**Current Behavior**
Specifically, if calling an Artifact API method (e.g., `alignment.methods.mafft`), the traceback is very similar if the input `Artifact` has an issue, or if the output (i.e., return from the API) `Artifact`s have an issue. It is implied deep in the traceback, but can easily lead to developer confusion about where an error lays.

**Comment by Oddant1** [comment]
I'm not certain what exactly this means? I'm not sure how we would differentiate beyond reading the traceback. If you have a good way forward here feel free to open a PR or drop your ideas here, but given that this is over 6.5 years old and hasn't been touched I'm going to close this for now.
