### ISSUE TITLE
better handling of unloadable artifacts

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#22]
It is primarily up to interfaces to determine how they handle discovering artifacts that they cannot load (either because the plugin that defines their type is not installed, or the `.qtf` file is corrupt), but QIIME 2 should likely raise a custom error type to make this easier for interfaces to detect. The corresponding error should differentiate corrupt artifacts from unimportable artifacts. If Artifacts encode information about the plugin that defines them in their metadata, an unimportable Artifact could tell the user what plugin needs to be imported for it to be used. 

Also, providing a non-qtf file should give a nice error message. The current message is something like: `tarfile.ReadError: '/Users/jairideout/dev/qiime2/q2-ninja-ops/seqs.fna' is not a readable tar archive file`.

**Comment by jairideout** [comment]
👴 👵
