### ISSUE TITLE
support exporting visualizations

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#226]
**Comments**
It would be useful to support exporting from visualizations in a particular rendering (e.g. HTML, PNG, PDF, etc.). This may be easier to accomplish if there was a manifest in the visualization format describing the different rendering that are available.

**Comment by rcsbiotech** [comment]
Agreed. I'm also trying to generate graphical reports without having to Print Screen, but it seems it's not possible.

**Comment by Oddant1** [comment]
This is largely already a thing now
