### ISSUE TITLE
Metadata / MetadataCategory types causing code duplication

### ISSUE THREAD

**Issue by mortonjt** [qiime2/qiime2#228]
**Current Behavior**
When I was coding up the q2 plugin for gneiss, the `Metadata` type created some confusion.

Specifically, the `Metadata` type as I understand is basically a wrapper around `pd.DataFrame`.  But it isn't a `pd.DataFrame`.  When I was registering functions in gneiss, I ran into this problem, and basically had to duplicate my function.  For example, the function [ols](https://github.com/biocore/gneiss/blob/master/gneiss/regression/_ols.py#L28) takes in a pandas DataFrame.  In order to register a function for this, I created a wrapper [ols_regression](https://github.com/biocore/gneiss/blob/master/gneiss/regression/_regression.py#L21) 

Now, there are quite a few functions in gneiss, and the number is growing very rapidly.  

**Proposed Behavior**
If the `Metadata` and `MetadataCategory` types could be directly mapped to `pd.DataFrame` or a `pd.Series`, that would reduce quite a bit of developer burden maintaining duplicate functions.

**Comments**
If you guys have other suggestions for avoiding code duplication in these sorts of scenarios, I'll be happy to hear your thoughts.  Thanks!

**References**
1. [ols](https://github.com/biocore/gneiss/blob/master/gneiss/regression/_ols.py#L28)
2. [ols_regression](https://github.com/biocore/gneiss/blob/master/gneiss/regression/_regression.py#L21)

**Comment by ebolyen** [comment]
This is a good issue, thanks for creating it!

I think the most obvious way to accomplish this would be to provide *view* capabilities to primitives (with some transformers). We've talked internally about this before in the past. I'm not sure if these would be registerable by plugins or if they would be baked into the framework. Given how much can go wrong with dataframes, I'm leaning towards the framework itself would be the only thing allowed to create primitive views. Most primitives also only have a couple sensible representations anyhow (or can "autobox" themselves like `np.int` <-> `int`).

**Comment by Oddant1** [comment]
@ebolyen This is kind of already a thing for Metadata in particular now isn't it? And we've talked a bit more about the whole deal with transforming primitives.
