### ISSUE TITLE
support configuration system

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#232]
**Comments**
For example, configuring a temp directory. 

**References**
See some discussion in #12.

**Comment by thermokarst** [comment]
Also, see stalled dev branch: https://github.com/thermokarst/qiime2/tree/field-on-fire

**Comment by bhillmann** [comment]
Any updates on the status of this enhancement? Or is it still baking in the kiln 🔥

**Comment by thermokarst** [comment]
@bhillmann, still cookin. This is currently on our radar for either our September or October 2017 releases. Stay tuned!

**Comment by MaestSi** [comment]
Hi, are there any news about the possibility to change QIIME2 tmp dir?
Thanks,
Simone

**Comment by thermokarst** [comment]
Hi @MaestSi - QIIME 2 inherits the Python behavior for this: https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

```
1) The directory named by the TMPDIR environment variable.
2) The directory named by the TEMP environment variable.
3) The directory named by the TMP environment variable.
4) A platform-specific location ...
5) As a last resort, the current working directory.
```

So if you want to change your temp dir, set one of the env vars listed above. As well, this has been discussed quite a bit over on the QIIME 2 forum (https://forum.qiime2.org).

Thanks!

**Comment by MaestSi** [comment]
Hi @thermokarst ,
thank you for the kind answer.
Simone

**Comment by Oddant1** [comment]
We have a config now (that is currently very limited in scope)

**Comment by colinbrislawn** [comment]
>We have a config now (that is currently very limited in scope)

Can you send me docs for this? [Old](https://forum.qiime2.org/t/dada2-set-tmpdir-permanently/10115) [topics](https://forum.qiime2.org/t/tmpdir-memory-error/11400) from the forums make it clear that setting `$TMPDIR` is the primary and recommended way to do this.

While I'm not opposed to env vars, I would love to try the new config method!
