### ISSUE TITLE
add TypeMap support if necessary

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#233]
**Comments**
e.g. filtering samples from a `FeatureTable[Frequency]` or a `FeatureTable[Composition]`

**References**
May not be necessary pending https://github.com/qiime2/qiime2/issues/192

**Comment by ChrisKeefe** [comment]
It's not super clear to me from the example what satisfies this issue. Should it be closed given https://github.com/qiime2/qiime2/pull/444?
