### ISSUE TITLE
support variadic inputs and outputs

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#234]

**Comment by gregcaporaso** [comment]
This should include zero inputs, which is necessary to support qiime2/q2-diversity#95.

**Comment by jairideout** [comment]
Note: zero inputs are supported as of 2017.6.

**Comment by ebolyen** [comment]
I could see two obvious ways to accomplish this, either we introspect the signature a little more and support `*args` (which limits us to a single variadic input, maybe that's good, maybe that's bad). 

Or we use the `List[...]` primitive with a semantic type in its field. This would take a little finagling (primitives and semantic types don't allow themselves to be mixed right now), but would allow you to have multiple variadic inputs.

**Comment by ebolyen** [comment]
We could even support both (perhaps supporting `*args` first, as it is probably the easier one to implement).

**Comment by wasade** [comment]
Copypasta from our Slack conversation on this:

"Is there an example of how to pass a `list` or `tuple` into a registered method? What I'm looking for specifically is to be able to do: `qiime foo --i-bar ax,bx,cx --i-baz ay,by,cy` or `qiime foo --i-bar ax --i-bar bx --i-bar cx --i-baz ay --i-baz by --i-baz cy` where `{ax, bx, cx, ay, by, cy}` are file paths and exiting types (e.g., `BIOMV210Format`, `NewickFormat`, etc), and are ordered such that, in the above, the following would be `True`: `[(i,j) for i, j in zip(bar, baz)] == [('ax', 'ay'), ('bx', 'by'), ('cx', 'cy')]`. Use case spans N bar and N baz tables, where N is [2, inf)."

**Comment by ebolyen** [comment]
`List[...]` and `Set[...]` are now supported as inputs. No output support yet.

**Comment by Oddant1** [comment]
@ebolyen unless I'm misunderstanding this is now finally basically closed with output collections
