### ISSUE TITLE
support for usage examples on methods/visualizers

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#237]
**Improvement Description**
It would be useful to support an API for registering usage examples with methods/visualizers. The usage examples would be described in a generic way (at the API level) so that interfaces can generate interface-specific usage examples (e.g. q2cli would generate command line-specific examples, q2studio would generate a series of screenshots or animated gif, etc.). 

**References**
These examples could also be displayed in the [plugin directory](https://docs.qiime2.org/2017.2/plugins/available/) (i.e. "script index").

**Comment by Oddant1** [comment]
We have this now
