### ISSUE TITLE
Help menu overflow due to too many options

### ISSUE THREAD

**Issue by mortonjt** [qiime2/qiime2#245]
This issue is raised in this [PR](https://github.com/biocore/gneiss/pull/151)

Basically if there are too many options, the user won't be able to view all of the options on the command line.  Definitely not ideal ...

There are hacks around this.  For example, you could pipe the std errors to a file for view everything.
Another option perhaps is to hack the unix `man` command to allow to the full help menu to be viewed through `more` or `less`.  Any thoughts?

**Comment by jairideout** [comment]
Moved to q2cli: https://github.com/qiime2/q2cli/issues/132
