### ISSUE TITLE
QIIME 2 Video Tutorials 

### ISSUE THREAD

**Issue by odetomyday** [qiime2/qiime2#246]
Hello! I created QIIME 1 installation video tutorials as part of my job at NC State's Biotechnology program. I have been given the green light to make some QIIME 2 tutorials for their [Youtube channel](https://www.youtube.com/channel/UCVAlAbkUIsn114Ucu8J1lHQ) as my time there is coming to an end, if there is interest. What video tutorials would be the most useful, if any?

**Comment by gregcaporaso** [comment]
Hi @odetomyday, Would you be able to get in touch with me on [Slack](https://slack.qiime2.org) to discuss? I think it'll be easier to go back and forth by instant messenger.
