### ISSUE TITLE
Make qiime2 python 3.6 compatible

### ISSUE THREAD

**Issue by johnchase** [qiime2/qiime2#250]
**Comments**
I realize this may not be a linear process, though it would be nice at some point. Additionally, while I don't know the specific incompatibilities, it may be useful to catalogue them here

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/how-to-install-qiime2-in-particular-artifact-api-with-current-conda-environment-mac-osx/4355/5?u=nicholas_bokulich)

**Comment by ebolyen** [comment]
Odds are pretty good that we'll be jumping to 3.7 once that's officially released. There's some language features that would be useful to have.

**Comment by jolespin** [comment]
@ebolyen do you have any insight if `skbio` will have a direct port to `Python 3.7`? I know the `qiime` uses `skbio` and I am looking forward to upgrading to `Python 3.7` once `qiime2` is compatible.

**Comment by ebolyen** [comment]
I suppose I don't have a timeline on that, but it will be a necessary for QIIME 2, so it'll certainly happen.

I think skbio and other dependencies are likely to be the slowest part of this process, but I expect in a month or two after the official release of 3.7 that dust will have settled.

**Comment by ChrisKeefe** [comment]
Closing - we're at 3.8 now.
