### ISSUE TITLE
Continue miniconda 2 support?

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#254]
Our docs state we support Miniconda 2, but we don't have any testing of this taking place in `busywork`.

**Comment by jairideout** [comment]
👍 for continuing Miniconda2 support unless it's prohibitive to do so (and 👍 for adding explicit testing to busywork). There's probably quite a few users who have existing Miniconda2 installs so it could be painful to have them nuke their entire `conda` install/envs just to use QIIME 2.

**Comment by thermokarst** [comment]
We have had a handful of users report successfully using miniconda 2 in their deployments, I think this issue is safe to close now.
