### ISSUE TITLE
Support multi-device filesystems

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#255]
QIIME 2 tries to be efficient by hardlinking anything it can, but a hardlink only works on a single device. A user on the forum [ran into this problem](https://forum.qiime2.org/t/error-with-qiime-tools-import/565).

It shouldn't be hard to fix, we just need to catch `OSError: [Errno 18] Invalid cross-device link` in the `InPath`/`OutPath` objects and back out to a copy instead.

**Comment by gregcaporaso** [comment]
@BenKaehler, does this sound like the issue that you recently ran into on your cluster? If so, would you be able to help us out with testing a fix for this when we're ready?

**Comment by BenKaehler** [comment]
Sorry @gregcaporaso, this isn't one of the errors that I observed. I think I had a different set of NFS-related problems.

**Comment by jairideout** [comment]
Fixed in #274.
