### ISSUE TITLE
Error: Qiime 2 plugin 'demux' has no action 'emp'

### ISSUE THREAD

**Issue by rimanasra** [qiime2/qiime2#257]
Hi, 
I am doing the tutorial with for qiime 2 (2017.4 installed) and I'm getting the following issues:
Error: QIIME 2 plugin 'demux' has no action 'emp'
![screenshot 2017-05-06 12 42 54](https://cloud.githubusercontent.com/assets/28489284/25774261/3f6f789a-325a-11e7-9215-75dc580b4435.png)

Thanks for the advice

**Comment by thermokarst** [comment]
Hi @rimanasra, can you please post this to the [QIIME 2 Forum](https://forum.qiime2.org) --- this is where we provide user support. Thanks!
