### ISSUE TITLE
Load text files in Artifacts as strings

### ISSUE THREAD

**Issue by jwdebelius** [qiime2/qiime2#258]
I have an artifact that I've generated with QIIME 2, although now I want to operate on it in python. I try to load into python

```python
import pandas as pd

from qiime2 import Artifact

alpha_  = Artifact.load(fp_).view(pd.Series)
```

In my exported series, my original barcode like, 10317.00001001 has been converted to something like 10317.00001.  When I export artifact into a text file, the sample ID are preserved. So, I think somewhere, python is doing data inference, possibly when the data is loaded as a series.

**Comment by ebolyen** [comment]
Nice catch! It's probably a transformer that is misbehaving. What does the `.format` property of your artifact say? It'll probably be a problem in the transformer from that format to `pd.Series`

**Comment by jwdebelius** [comment]
The format is
`qiime2.plugin.model.directory_format.AlphaDiversityDirectoryFormat`

I've used a lot of pandas, and I rarely have an issue with pandas inferring data types once something is loaded into the memory. 
My suspicion is that the problem comes from when the data is loaded using the pandas API. I  usually solve this by loading dataframes as text, and then casting during analysis. I think, though, you can also specify column-data type pairs with the dtype parameter.

**Comment by ebolyen** [comment]
cross-referencing a similar problem: https://github.com/qiime2/q2-diversity/issues/91
