### ISSUE TITLE
Interactive Sample Detail, question/bug?

### ISSUE THREAD

**Issue by antgonza** [qiime2/qiime2#276]
During the ASM workshop a user pointed out that the "Sequences Retained: 0 (0.00%)" field is confusing, which I agree. The confusing points are:
- It starts in 0 with 0.0% retained, where it should be 100%, right?
- Once you start moving to the right, it seems to be going up so showing the sequences removed (not retained) and then once you get to around (50%) it starts going up, see screenshot.
![question](https://cloud.githubusercontent.com/assets/2014559/26791463/6eed0e34-49d4-11e7-9642-cbf451c0d691.gif)

**Comment by thermokarst** [comment]
Thanks @antgonza! I moved this over to the relevant [issue tracker](https://github.com/qiime2/q2-feature-table/issues/110). Thanks!
