### ISSUE TITLE
Need more space in provenance for commands with multiple inputs

### ISSUE THREAD

**Issue by JTFouquier** [qiime2/qiime2#290]
If you have multiple inputs, you don't have enough room for the provenance graph. More default space would be nice. :) Not very important though. 

<img width="960" alt="screen shot 2017-06-24 at 3 41 16 pm" src="https://user-images.githubusercontent.com/7920357/27512139-0d8a1392-58f4-11e7-8c6c-e6b72e67ef39.png">

**Comment by jairideout** [comment]
Thanks @JTFouquier! I [ported the issue](https://github.com/qiime2/q2view/issues/61) to q2view's issue tracker.
