### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#3]
@colinbrislawn has expressed interest in working on this [here](https://github.com/biocore/conda-recipes/issues/61). 

@colinbrislawn, let's primary track this one here. We'll follow up with you via this issue soon.

**Comment by colinbrislawn** [comment]
Sure thing greg. Thanks!

**Comment by jairideout** [comment]
We have conda packages of the various QIIME 2 alpha releases available under the [qiime2 conda channel](https://anaconda.org/qiime2). The wiki [has instructions](https://github.com/qiime2/qiime2/wiki/Publishing-a-plugin-on-conda) for how to build a conda package for plugin/interface developers.
