### ISSUE TITLE
Plugin error from dada2

### ISSUE THREAD

**Issue by michoug** [qiime2/qiime2#308]
Dear all,
I'm using qiime version 2017.6.0 installed via conda as described in the install pages
My OS is macOS Sierra

I tried to run the tutorial available here : https://docs.qiime2.org/2017.6/tutorials/moving-pictures/
When I run the command :

```
qiime dada2 denoise-single \
  --i-demultiplexed-seqs demux.qza \
  --p-trim-left 0 \
  --p-trunc-len 120 \
  --o-representative-sequences rep-seqs-dada2.qza \
  --o-table table-dada2.qza
```

I get this error : 

> Plugin error from dada2:
> 
>   Command '['run_dada_single.R',
>   '/var/folders/kc/5v4myfjd0c79525lmjsjtyrh9hqckl/T/qiime2-archive-
>   nxksanwe/39fd29b1-7775-4335-bd47-46e4931461d1/data', '/var/folders/kc/
>   5v4myfjd0c79525lmjsjtyrh9hqckl/T/tmphow57op1/output.tsv.biom',
>   '/var/folders/kc/5v4myfjd0c79525lmjsjtyrh9hqckl/T/tmphow57op1', '120',
>   '0', '2.0', '2', 'consensus', '1.0', '1', '1000000']' returned non-
>   zero exit status -11
> 
> Debug info has been saved to /var/folders/kc/5v4myfjd0c79525lmjsjtyrh9hqckl/T/qiime2-q2cli-err-2rcdyb89.log.

The log is attached

[qiime2-q2cli-err-369kxu8v.txt](https://github.com/qiime2/qiime2/files/1169641/qiime2-q2cli-err-369kxu8v.txt)

**Comment by thermokarst** [comment]
@michoug , can you please post your question on the [QIIME 2 forum](https://forum.qiime2.org)? That's where we provide user support. Thanks!
