### ISSUE TITLE
create a mechanism for importing data into artifacts

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#31]
I have an [old gist](https://gist.github.com/gregcaporaso/edbe4135dd870bb606f9) that illustrates how to do this - that code may or may not still work, but the idea is the same. 

As of now, on import ``provenance`` should be ``None``, but we likely want to provide some provenance information for these, such as when the file was uploaded, the source file path, etc.

**Comment by jairideout** [comment]
Copying these instructions for importing an artifact from q2d3 README.md since they're about to be deleted:

```python
from feature_table.artifact_types import FeatureTable, Frequency

import biom
biom_path = "./otu-table.tsv"
table = biom.load_table(biom_path)

from qiime.sdk import Artifact
Artifact.save(table, FeatureTable[Frequency], None, "./example-table.qtf")
```

**Comment by gregcaporaso** [comment]
This might makes sense as a workflow in the ``q2_types`` plugin.

**Comment by jairideout** [comment]
👎, turning data into artifacts is a general operation (regardless of semantic type or what plugins you have installed) so makes sense in the framework's SDK. A developer should be able to import data into artifacts without having the domain-specific `q2_types` plugin installed.
