### ISSUE TITLE
how to use .py source file 

### ISSUE THREAD

**Issue by HugoCode** [qiime2/qiime2#315]
I have installed qiime2017.7 with miniconda3 in linux , but I can not find where qiime's .py source file, so I don't know how to use .py's function.

**Comment by thermokarst** [comment]
Hi @HugoCode, can you please ask this over on our [Support Forum](https://forum.qiime2.org)? The Forum is where we provide user-support. Thanks!

**Comment by HugoCode** [comment]
ok，thank you
