### ISSUE TITLE
R version. only R3.3.1 works but not R 3.4.1.

### ISSUE THREAD

**Issue by hshcao** [qiime2/qiime2#316]
QIIME2 only works with R3.3.1 but not R3.4.1 (the current latest version) under linux. and installing older versions R is really painful in linux. 
is there a way to install R3.3.1 with miniconda3 during QIIME2 installation or can you update R to 3.4.1 version.

Thank you.

Best,

Huansheng

**Comment by jairideout** [comment]
Hi @hshcao, can you please ask this over on our [Support Forum](https://forum.qiime2.org)? The Forum is where we provide user-support. Thanks!

**Comment by hshcao** [comment]
thank you. I will do that.
