### ISSUE TITLE
`Str % Choices` with empty iterable should error

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#321]
Defining `Str % Choices` without any choices (i.e. empty iterable) returns a `Str`:

![image](https://user-images.githubusercontent.com/1847232/29591075-e27fff54-876a-11e7-896e-d53125eec474.png)

I saw this when reviewing the [alpha-rarefaction PR](https://github.com/qiime2/q2-diversity/pull/128). The `metric` parameter was defined as `Str % Choices` using a dynamically computed `set`, which (by accident) was always an empty `set`. This caused the primitive type to become `Str` (dropping the `Choices` predicate).

I think the type system should raise an error if there are empty `Choices` in order to help developers catch bugs. I can't think of a case where devs would need to define empty `Choices`.

**Comment by ebolyen** [comment]
fixed in #349
