### ISSUE TITLE
`Choices` predicate should preserve order.

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#323]
**Comments**
This will make interface generation more predictable. However it may imply that:
```python
Str % Choices('a', 'b', 'c') != Str % Choices('b', 'c', 'a')
```
which after looking at the grammar again, should be fine as we have a `equals` (`a <= b <= a`) method to check domain equality. `__eq__` is strictly for hashing and matches `__hash__`'s semantics

**Comment by Oddant1** [comment]
Seems like we tend to just give it a list which is of course ordered, so maybe we don't need this anymore. @ebolyen open if you think is still relevant
