### ISSUE TITLE
Rename MetadataCategory to MetadataColumn

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#326]
As we start typing these columns (numeric, categorical), category starts to sound weird. We are at the point where we can still feasibly change this.

**Comment by antgonza** [comment]
Just for clarity, in theory this issue should be solved first, then https://github.com/qiime2/qiime2/issues/297, and finally https://github.com/qiime2/qiime2/issues/327, right? 

I _think_ I can help with this but not sure if that's correct and if so, my next question is: do we have code to define what's numeric and categorical? If we do, what about those columns that are numerical and have "None" values, including [these](http://www.ebi.ac.uk/ena/about/missing-values-reporting) INSDC missing value reporting terms?

**Comment by jairideout** [comment]
These are great questions! We're scheduling a call for 2017.10 to talk about all of these metadata-related issues and we can triage tasks at that point -- your help would be greatly appreciated! We'll include you on that call if you're interested.

**Comment by antgonza** [comment]
I'll be interested!

**Comment by jairideout** [comment]
Great, we'll get in touch when we're scheduling the call! :phone:

**Comment by jairideout** [comment]
Fixed in #359. `qiime2.MetadataCategory` is now `qiime2.MetadataColumn` (an abstract base class), which has two concrete subclasses, `CategoricalMetadataColumn` and `NumericMetadataColumn`.
