### ISSUE TITLE
add support for action parameters to accept more than one type

### ISSUE THREAD

**Issue by nbokulich** [qiime2/qiime2#331]
E.g., a parameter that accepts a `Str` or `Int` as input.

Is what I am describing a [union type](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#union-types)? This would be EXTREMELY useful.

Example use: some seaborn plotting functions support int or str inputs for defining confidence intervals (for generating ci range or using standard dev instead), and I would like to propagate this flexibility in visualizers that call these functions.

I originally had this in mind for primitives, but if this can be expanded for artifacts that would be useful also. For example, an action could accept a `FeatureTable[Frequency]` OR `FeatureTable[RelativeFrequency]`. For some actions, it makes sense to accept different semantic types.

**Comment by ebolyen** [comment]
It is a union type! 

And we do already support it for semantic types (e.g. `FeatureTable[Frequency | RelativeFrequency]`), but not for primitive types yet. There is a slight mechanical problem of how you interpret `"3"` from an interface in the context of `Str | Int` which makes things a little fuzzy. This is why we didn't let primitives support unions until it become clearly necessary. But I think the above can be worked around.

**Comment by nbokulich** [comment]
😲 that is very good news to hear about semantic types!

Could use of quotes be a way to explicitly define whether a numerical input should be interpreted as `Int`/`Float` or `Str`?

**Comment by ebolyen** [comment]
Semantic types closed in who knows what PR; Unions of primitives are captured by issue #409
