### ISSUE TITLE
bad error message on incorrectly formatted metadata

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#335]
I was working with a user who had a strange formatting issue in the sample metadata file - basically all lines except the header had a trailing tab character. Here's a view of the file with visible spaces:

![screenshot 2017-09-19 14 16 41](https://user-images.githubusercontent.com/192372/30608132-5e3abd4c-9d45-11e7-9542-cd1f37819cb0.png)

When using this file to demultiplex, the user got the following error:

```
Plugin error from demux:
 
  A duplicate barcode was detected. The barcode ACTCCTRCGGGAGGCAGCAG was
  observed for samples AATGAGCGGAGCCTTA and AATGAGCGAAGGCTAT.
```

Checking under the hook, we can see that the file wasn't parsed correctly:

```
In [2]: from qiime2 import Metadata

In [3]: md = Metadata.load('./sample-metadata.tsv')

In [4]: md
Out[4]:
                       BarcodeSequence LinkerPrimerSequence
#SampleID
AATGAGCGAAGGCTAT  ACTCCTRCGGGAGGCAGCAG                  NaN
AATGAGCGGAGCCTTA  ACTCCTRCGGGAGGCAGCAG                  NaN
ACGAATTCAAGGCTAT  ACTCCTRCGGGAGGCAGCAG                  NaN
ACGAATTCGAGCCTTA  ACTCCTRCGGGAGGCAGCAG                  NaN
```

Not sure exactly what's happening behind the scenes (I think it's in pandas), but the barcodes are becoming the sample ids, and the `LinkerPrimerSequence` becomes the `BarcodeSequence` column. 

Keemei validation passed on this file. 

It's not exactly clear what we want to do here for now (and it's an unusual case, so not urgent), but it's probably something to check for when we have detailed validation of metadata hooked up. 

Removing the extra tab from each line in the file caused this to parse correctly:

```
In [5]: md = Metadata.load('./sample-metadata-fixed.tsv')

In [6]: md
Out[6]:
             BarcodeSequence  LinkerPrimerSequence
#SampleID
PCRNTC1     AATGAGCGAAGGCTAT  ACTCCTRCGGGAGGCAGCAG
PCRNTC2     AATGAGCGGAGCCTTA  ACTCCTRCGGGAGGCAGCAG
PCRNTC3     ACGAATTCAAGGCTAT  ACTCCTRCGGGAGGCAGCAG
PCRNTC4     ACGAATTCGAGCCTTA  ACTCCTRCGGGAGGCAGCAG
```

**Comment by jairideout** [comment]
Sounds like pandas is doing something strange -- we might want to scrap `pandas.read_csv` and use Python's `csv` module, it behaves more sanely in general (haven't verified what it does in this case though).

Out of curiosity, how was this file created? Keemei would just ignore that extra column since there's no data -- it only validates the "extent" of a spreadsheet (i.e. the bounding box that captures all data in the sheet). Exporting the data as TSV from Google Sheets shouldn't add an extra empty column, unless something changed on Google's end recently.

**Comment by gregcaporaso** [comment]
I'm not exactly sure how it was generated, but I'm guessing Excel. It was provided by the group who did the sequencing. The version I ran this with was not exported from Google Docs (so there's no reason to think anything has changed there) - I just tried validating the file with Keemei after seeing the error, and then tried parsing the local copy of the file that I had with `qiime2.Metadata`.

**Comment by jairideout** [comment]
Thanks for the details @gregcaporaso!

**Comment by jairideout** [comment]
I dug into this for 2017.9 but didn't have much luck. There are several variations of @gregcaporaso's data that I was able to create that cause pandas to behave in strange (and unique) ways. The only way I can see to solve this (with the current parser that uses pandas) is to disallow columns that only contain NaNs for their values. This gets into a bigger discussion about allowing/disallowing empty columns in metadata, which is scheduled for 2017.10, so I'll bump this issue to next release.

**Comment by antgonza** [comment]
Right, this is what we saw in Qiita and the main reason to do it in 2 steps verification as mentioned in https://github.com/qiime2/qiime2/issues/336

**Comment by jairideout** [comment]
The new Metadata parser is able to load this weird jagged data correctly now (see #359 and #360).
