### ISSUE TITLE
QIIME 2 plugin 'diversity' has no action 'core-metrics-phylogenetic'

### ISSUE THREAD

**Issue by slh277** [qiime2/qiime2#343]
Hello, and apologies in advance for what is probably a very basic question:

I am working through the Moving Pictures Tutorial and I have gotten up to doing the diversity analysis. however when I type in 
```
qiime diversity core-metrics-phylogenetic \
  --i-phylogeny rooted-tree.qza \
  --i-table table.qza \
  --p-sampling-depth 1109 \
  --output-dir core-metrics-results
```

the output is: 
QIIME 2 plugin 'diversity' has no action 'core-metrics-phylogenetic'

However, If I do the same thing but without "phylogenetic" on the end...
```
qiime diversity core-metrics \
  --i-phylogeny rooted-tree.qza \
  --i-table table.qza \
  --p-sampling-depth 1109 \
  --output-dir core-metrics-results
```

It works. But what is the reason for the first problem?

**Comment by ebolyen** [comment]
Hi @slh277, this is better posted on the [QIIME 2 Forum](https://forum.qiime2.org), but to answer briefly: We [just released](https://forum.qiime2.org/t/qiime-2-2017-9-release-is-now-live/1160) a new version `2017.9` which has both: 
 - `core-metrics` (no phylogenetic metrics) 
 - `core-metrics-phylogeny` (formerly `core-metrics` in older versions). 

We recommend [installing the latest](https://docs.qiime2.org/2017.9/install/native/) version!
