### ISSUE TITLE
Track citations in provenance

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#344]
Depends/related to #113 

This would involve plugin-level, action-level, and potentially even transformer/format-level citations.

Once recorded, q2view or other interfaces could demonstrate what tools should be cited for any given artifact/visualization.

**Comment by ebolyen** [comment]
Here's an initial sketch of what this would look like:

### \<uuid>/provenance/action/action.yaml:
```text
execution:
    ...
action:
    type: method
    action: mask
    ...
    citations:
        - !cite 'action:alignment.method.mask:2018.4.0:0'
        - !cite 'action:alignment.method.mask:2018.4.0:1'
    ...
    inputs:
    ...
transformers:
    - plugin: !ref 'environment:plugins:types'
      from: SomeKindOfFormat
      to: biom.table.Table
      citations:
          - !cite 'view:types:biom.table.Table:2018.4.0:0'
environment:
    ...
    plugins:
        types:
            citations:
                - !cite 'plugin:types:2018.4.0:0'
            ...
        alignment:
            citations:
                - !cite 'plugin:aligment:2018.4.0:0'
            ...
        ...
```

### \<uuid>/citations.bib:
```text
@article{action:alignment.method.mask:2018.4.0:0,
...
}
@article{action:alignment.method.mask:2018.4.0:1,
...
}
@article{view:types:biom.table.Table:2018.4.0:0,
...
}
@article{plugin:types:2018.4.0:0,
...
}
@article{plugin:aligment:2018.4.0:0,
...
}
@article{annotation:63cb9f47-c5c2-4a80-8449-b7210f634f6f:0,
...
}
```

### Some additional thoughts:
Someday I think we're going to want to support adding annotations/comments/additional citations to arbitrary nodes in an artifact. 
**I do not think that doing so should impact the UUID** because whether an artifact has been annotated has no real bearing on what the computer will do. Furthermore, it makes more sense from a user-perspective to annotate retroactively. If this required a brand new intermediate artifact, then they would need to redo their analysis to retain provenance, which defeats the entire purpose.

Given that, if we are careful about how annotations are stored, it would be possible for annotations to be added in an interface like q2view. Because these are zip files, appending new information is actually really simple, it should be possible then for q2view (or a similarly "simple" interface) to allow users to annotate and add additional citations which are then "streamed" into the end of the file if they choose to save the new version.

For that, annotations and citations should be stored in files that are easy to append to. Fortunately bibtex is one such format, and so we would expect to see those kinds of annotations at the end of the file. For example, a Greengenes QZA would have an obvious citation.

### The keys:

I'm open to other citation-key formats. I think the *key* idea, is that there would be a `!cite` type which acts just like `\cite{<some key>}` in LaTeX. Including a top level category (action, view, plugin, annotation) makes it easy to differentiate the keys, but probably isn't technically necessary. Using the plugin/action and version to reference a citation instead of the action UUID makes it easier to deduplicate citations since odds are pretty good that you will see the same action performed a couple of times from the same version of QIIME 2 in very downstream visualizations.

**Comment by antgonza** [comment]
I _think_ makes sense. A couple of questions:
1. Would it be possible to export the citations to something like endnote? What it will be pretty great will be to add it there in "full" format and then let endnote/word format depending on paper. I'm not really sure how this will work, I _normally_ just add via PMID and let endnote do all the parsing/formatting.  
2. What about citations for the method and then for the plugin? For example, sklearn in feature-classifier.

**Comment by ebolyen** [comment]
Thanks for reading @antgonza!

Re 1: I think initially we would export a fully collated and de-duplicated list in bibtex. From there, it looks like you could convert to endnote's XML format through some conversion utilities. I don't see why we couldn't support that in the future though! We just need someone who knows how that format works.

Re 2: Yup! In provenance we would be able to have independent citations in both the `action` section and the `environment.plugins` section which should handle your example.

**Comment by wasade** [comment]
This is really cool! One observation, some methods such as `q2_diversity.beta_phylogenetic` have citations that are only relevant given user-oriented parameter choices. For example, in `beta_phylogenetic_alt`, citing Generalized UniFrac is only relevant if `--p-alpha` is specified. Similarly, in both `beta_phylogenetic` and `beta_phylogenetic_alt`, the citation for weighted UniFrac differs from unweighted UniFrac (I'm not sure if this distinction is always made in the literature), but the specific metric used is controlled via `--p-metric`. I _think_ the correct perspective here is "sub-action" granularity. I just wanted to mention these examples as they potentially exist in other plugins, and I don't think they're scoped in the discussion so far -- I apologize though if it is and I overlooked it.

**Comment by ebolyen** [comment]
That is a really good point @wasade, I had overlooked that.

**Comment by ebolyen** [comment]
Alright, here's a couple of options to handle sub-action citation:

1. We do nothing. Not a great solution, but since action citations are a list, maybe in the future we figure out a good way to handle it and we just append in the future. The yaml/bib files won't notice, their payload just becomes more dynamic than it was before.

(Choosing option 1 doesn't preclude any of the following options in the future as far as I can tell)

2. We change all methods to become more atomic so that their citation is always accurate. Suddenly we have a bajillion small methods for distance calculations (and whatever else this "rule" might capture). Probably not the most user-friendly option.

2. We create some kind of optional static mapping of value(s) to citation for every parameter. :nose:-goes on who get's to write that annotation. Downside of this, is there are probably situations where a technique could be applied heuristically and so can't be cited in a static way. (Although arguably maybe it should always be cited, if the technique always has the potential to be applied.)

3. We create a dynamic API for appending citations. This requires some kind of DI'ed object in the signature, but QIIME 2 does that all the time (for example `ctx` and `output_dir`). Speaking of which, perhaps Pipelines are the easy way out. There could be a method `ctx.add_citation()` which can be called at any point within a pipeline. Methods that have sub-action citations are just promoted to very simple pipelines.

4. The dynamic API shares something with logging and is accessible to any action. This is basically the same as 3, but the API is something like `log` instead of `ctx`. An argument could probably also be made that it would be useful to have context-aware actions anyways, so maybe `ctx` should always be available (or at least requestable).

**Comment by thermokarst** [comment]
Replies to https://github.com/qiime2/qiime2/issues/344#issuecomment-369688833

> Someday I think we're going to want to support adding annotations/comments/additional citations to arbitrary nodes in an artifact.

👍 Annotations have been requested a few times, including by non-microbiome-type users interested in decentralized provenance at Plotcon Spring 2017.

> I'm open to other citation-key formats.

Me too, but I do like focusing on bibtex for now - it is ubiquitous, well defined, and doesn't require us to invent Yet Another Citation Format ™️ .

> Lists for multiple citations on a given "node" are implied by the bibtex citation-key using a trailing :0, :1, ... :N, but any other scheme would work.

🆒 

---

Replies to https://github.com/qiime2/qiime2/issues/344#issuecomment-369930873

I really like the idea of option 4 here --- besides citations, I wonder if the parameter-based method branching in `beta_phylo_alt` would be more clear as a pipeline, anyway --- it would require less intrinsic knowledge of what params map to what internal methods, esp. when interrogating provenance. I know one issue here is then we would have a ton of new methods, so that is something to consider.

**Comment by antgonza** [comment]
I agree on @thermokarst comments and the preferring option 4.

Now, in the other topic of parameters, something to consider is that each of the different methods in beta/alpha diversity should have it's own citation, which might create an explosion of parameters as there is always new ways to estimate this values. Within Qiita we have been collecting this information, in case it's of interest, for example [for beta diversity](https://qiita.ucsd.edu/static/doc/html/analyzingsamples/index.html#calculating-beta-diversity).

**Comment by ebolyen** [comment]
Re: https://github.com/qiime2/qiime2/issues/344#issuecomment-369947463

>  Me too, but I do like focusing on bibtex for now - it is ubiquitous, well defined, and doesn't require us to invent Yet Another Citation Format tm .

I agree, I would say I'm pretty set on using bibtex internal to the archive for all the reasons you list and it's very append-friendly (vs an XML DOM or YAML/JSON schema).

Also, just to clarify, that section was about strings like this: `action:alignment.method.mask:2018.4.0:0` which are the "citation key" (`\cite{action:alignment.method.mask:2018.4.0:0}`). The key itself is ultimately super arbitrary.

> it would require less intrinsic knowledge of what params map to what internal methods, esp. when interrogating provenance. I know one issue here is then we would have a ton of new methods, so that is something to consider.

Another option is to make a black-box pipeline, where it doesn't actually call any methods, it just consumes and spits out an artifact/visualization from some view.

And yet another thought: what if you could create "hidden" actions, which weren't generally accessible in an interface unless you said a magic word or whatever. These could be tracked and used by pipelines and provenance, but don't otherwise get in the way.

---

Re: https://github.com/qiime2/qiime2/issues/344#issuecomment-369950597

> which might create an explosion of parameters as there is always new ways to estimate this values

I believe that ship has already sailed for QIIME 2, there's a great many metrics you *could* supply to `alpha`/`beta`, though they are mostly unused as far as we can tell (`core-metrics` is just much easier).

> Within Qiita we have been collecting this information, in case it's of interest, for example for beta diversity.

That's a very handy list, thanks for sharing!

**Comment by thermokarst** [comment]
> And yet another thought: what if you could create "hidden" actions, which weren't generally accessible in an interface unless you said a magic word or whatever. These could be tracked and used by pipelines and provenance, but don't otherwise get in the way.

I was wondering the same thing! 👍 👍 👍

**Comment by antgonza** [comment]
> I believe that ship has already sailed for QIIME 2, there's a great many metrics you could supply to alpha/beta, though they are mostly unused as far as we can tell (core-metrics is just much easier).

Just to be clear, core-metrics works nicely for most of our cases cause we are lucky (❔) but other target genes (ITS1, ITS2, etc) and fields (metagenomics, proteomics, etc ...) actually need access to all those metrics.

**Comment by ebolyen** [comment]
The more I think about it, the more "hidden actions" make sense. 

Just the other day I was wishing I could run hamming on a presence-absence table, if that was a concrete action, then it's input type could have accepted P/A  *and* I would have gotten an appropriate static citation for it in my provenance.

We can still have convenience actions like `beta` and `alpha`, which is the entire purpose of a pipeline, but still compose the individual elements in a robust way for other uses, which is the point of a method. You can even imagine having DAG parallelism happen inside of the pipelines if they computed several metrics (that requires variadic output, but I could see that being handy in the future).

Another good example is UPGMA, it's an internal function in beta-rarefaction since usually you *need* some kind of support calculation for sample-clustering, but I'm working on a project that is clustering features, and I had to re-implement that internal function.

**Comment by ebolyen** [comment]
Random thought: what if hidden actions just started with an underscore? Then no new machinery is needed in the framework, and very few changes in the client UIs

**Comment by thermokarst** [comment]
Oh I like that plan. Will stew on it for a bit.
