### ISSUE TITLE
Metadata index can't handle value 'NA'

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#345]
The pandas parsing interprets `'NA'` as `np.nan`, causing an index validation error. I suspect this also happens if a column name is `'NA'`, too. 

This recently[ came up on the forum](https://forum.qiime2.org/t/metadata-index-error/1394).

**Comment by ElDeveloper** [comment]
I've faced this issue, and solved it by setting the `na_values=[], keep_default_na=False` arguments.

**Comment by antgonza** [comment]
Suggest taking a look at the Qiita [load_template_to_dataframe function](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/util.py#L170). It literally took us years to get it right (with multiple users updating templates) and we haven't had an issue in a while.

**Comment by thermokarst** [comment]
This came up [on the forum](https://forum.qiime2.org/t/metadata-error-in-diversity-core-metrics-pipeline/2177?u=thermokarst).

**Comment by jairideout** [comment]
[forum x-ref](https://forum.qiime2.org/t/sample-metadata-featuretable-graphs-question-on-unlabeled-column/2485/10?u=jairideout)

**Comment by jairideout** [comment]
Fixed in #359; confirmed that IDs and columns can be named `NA`, which is no longer interpreted as a missing value.
