### ISSUE TITLE
improve tutorials

### ISSUE THREAD

**Issue by antgonza** [qiime2/qiime2#346]
I think we need to add to the tutorial(s), somewhere:
- [ ] alpha rarefaction
- [ ] beta rarefaction
- [ ] others?

Also, not sure if worth revising the use of _ vs - because for some outputs we have _ and for others -. I think standardizing to _ will be nice cause that way you can "auto select" by double clicking.

**Comment by thermokarst** [comment]
Thanks @antgonza!

I am closing this to move (and split) to the appropriate [issue tracker](https://github.com/qiime2/docs/issues/)

- alpha rarefaction(dupe) https://github.com/qiime2/docs/issues/207
- beta rarefaction (new) https://github.com/qiime2/docs/issues/209
- hyphen vs underscore (new) https://github.com/qiime2/docs/issues/210

**Comment by antgonza** [comment]
Thanks.
