### ISSUE TITLE
Can qiime2 be used for the PacBio SMRT Cell data ?

### ISSUE THREAD

**Issue by jinhao94** [qiime2/qiime2#361]
Hi everyone,
When I ues a 16s full-length sequence in qiime2 for analysis，there are some problems in step “Sequence quality control and feature table construction”. As shown below： 
DADA2 R package version: 1.6.0 
1) Filtering .........
2) Learning Error Rates
Initializing error rates to maximum possible estimate.
Error in dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),  : 
  Input sequences exceed the maximum allowed string length.
Calls: dada -> dada_uniques -> .Call

My concerns boil down to two questions:
I haven't been able to find any information regarding whether qiime2 is suitable for use on PacBio SMRT Cell data. Does qiime2 not apply to the PacBio SMRT Cell data？
Thanks,
jin

**Comment by thermokarst** [comment]
Hi @jinhao94! Can you please ask this question over on the [QIIME 2 Forum](https://forum.qiime2.org)? That is where we provide user support. Thanks!
