### ISSUE TITLE
add `Metadata.peek` and connect to cli 

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#363]
Currently the only (planned) way to directly see the metadata column types using the command line is through `qiime metadata tabulate` (pending https://github.com/qiime2/q2-metadata/issues/3). If a user is editing their `#q2:types` info or their metadata values to alter the types, generating the viz will get annoying (it’s kind of like iterating with the QIIME 1 `validate_mapping_file.py` script). We should add a utility in `qiime tools` that would print the column names and their types. This could also be useful for figuring out what the column names are when viewing an artifact as metadata.

**Comment by ebolyen** [comment]
I think on the framework, this is already accomplished via the object repr and the `.columns` property. We can probably just present that info in q2cli (which I think is all you are really asking for).

If we did want a `peek` method in the framework, it kind of implies some partial loading of the file, which might be useful, but also seems like a lot of work for something that usually doesn't take much time in the first place.

---

What would you think about creating a command like `qiime tools columns` or `qiime tools cols`? I don't think we would want to put this functionality in `qiime tools peek` as that actually avoids loading artifacts. To view the columns of an artifact (which would be amazing), you would need to invoke a transformer which would take a lot longer than just "peeking" at `/<uuid>/metadata.yaml`. 

There could be a flag like `qiime tools peek --with-metadata`, but it starts to get messy, and it makes looking at `sample-metadata.tsv` a little awkward (do I include it or not if that's my only argument)?

**Comment by jairideout** [comment]
:+1:, this plan sounds great! What about using a slightly more descriptive name to help users out? A couple of ideas that come to mind are `qiime tools metadata-columns`, `qiime tools inspect-metadata`, or `qiime tools summarize-metadata`. I like the latter two options a little more than the first option because the names are more general, allowing other types of info to be displayed there in the future.

**Comment by ebolyen** [comment]
Awesome, I'm going to close this issue then and create a relevant one on q2cli!
