### ISSUE TITLE
Issue with generate rep-seqs-dada2.qza file

### ISSUE THREAD

**Issue by zhangbw777** [qiime2/qiime2#365]
Hello I tried two command
qiime vsearch dereplicate-sequences \
--i-sequences demux-single-end.qza \
--o-dereplicated-table table-dada2.qza \
--o-dereplicated-sequences rep-seqs-dada2.qza \

and command
qiime dada2 denosise-single \
--i-demultiplexed-seqs demux-single-end.qza \
--p-trim-left 0 \
--ptrunc-len 400 \
--p-n-threads 4 \
--o-table table-dada2.qza \
--o-representative-sequences rep-seqs-dada2.qza

but these commands only generate table-dada2.qza for me, there is no rep-seqs-dada2.qza.

Coould anyone help me, find out what part of my command went wrong?

Thanks for your help

**Comment by thermokarst** [comment]
Hi @zhangbw777, can you please ask this question on the QIIME 2 forum at https://forum.qiime2.org - that is where we provide user support. Thanks!

**Comment by zhangbw777** [comment]
Ok thanks Matthew. I will do that
