### ISSUE TITLE
q2_metadata

### ISSUE THREAD

**Issue by 110147** [qiime2/qiime2#386]
I'm very honour to test the sofe about qiime2 ,but I have a question about taxa , when I use the q2 to classify-sklearn my sequence ,I find the result just have the class classify is bacteria ,when I use the model data ,I can use success to annotation sequence species .so I want to know how to do and I also want to know about the personalized database use the command Train the classifier Whether or not classifier my own data ?thank you .

**Comment by thermokarst** [comment]
Hi @110147 - please ask this question on the [QIIME 2 Forum](https://forum.qiime2.org) - that is where we provide user support. Thanks!
