### ISSUE TITLE
How many cpu qiime use when running?

### ISSUE THREAD

**Issue by letunglam1991** [qiime2/qiime2#392]
when i run qiime2, i found maybe it only use 1 cpu. I have cpu with 12 cores, so how to setting for qiime use more cores? i think when use more cores qiime can run faster
![qiime](https://user-images.githubusercontent.com/34736243/38918001-971548fe-4316-11e8-93bf-4dd31ee40579.png)

**Comment by thermokarst** [comment]
Hi @letunglam1991 - can you please ask this question over on the [QIIME 2 Forum](https://forum.qiime2.org)? That is where we provide user support for the QIIME 2 project. Thanks!
