### ISSUE TITLE
function request: per sample filtering

### ISSUE THREAD

**Issue by qiyunzhu** [qiime2/qiime2#396]
Hello qiime2 team, this is Qiyun Zhu from the Knight Lab. We (@wasade @tanaes) recently realized that filtering out low-abundance taxa on a **per-sample** base can effectively reduce table density, and improve the resolution of downstream beta diversity analysis, especially for those unweighted metrics. To my understanding, both QIIME1 and 2 do not have the function for per-sample filtering. Would it be a good idea to add this function?

The implementation should be very simple. My solution (using the biom library) is:

```
th = 0.001  # threshold, which is a fraction

def filter_otus(data, id_, md):
    bound = data.sum() * th
    data[data < bound] = 0
    return data

table.transform(filter_otus, axis='sample')
table.remove_empty(axis='observation')
```

**Comment by thermokarst** [comment]
@qiyunzhu - can you please post this to the [q2-feature-table issue tracker](https://github.com/qiime2/q2-feature-table/issues) - thanks!

**Comment by qiyunzhu** [comment]
Hi @thermokarst thanks for pointing me to the right place! I just created an issue there [#177](https://github.com/qiime2/q2-feature-table/issues/177).

**Comment by thermokarst** [comment]
Thanks @qiyunzhu! We are going to write up some documentation on where and how to file these kinds of requests in the future, so sorry for not having that in place now! Thanks for your patience!

**Comment by qiyunzhu** [comment]
@thermokarst not a problem at all! You guys are doing a wonderful work!
