### ISSUE TITLE
cookiecutter for plugin packages

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#4]
[cookiecutter](https://github.com/audreyr/cookiecutter) may be useful for creating a standardized QIIME 2 plugin package structure (thanks @wasade for finding this!).

**Comment by souravsingh** [comment]
I would like to work on the issue.How do I start?

**Comment by jairideout** [comment]
Thanks for your interest in working on this @souravsingh! We are actively developing the base framework for QIIME 2 and the plugin architecture; this should be done within the next few weeks. Once that's ready we'll follow up here with details about a standardized plugin package structure.

**Comment by souravsingh** [comment]
Is the framework for the plugin available?

**Comment by gregcaporaso** [comment]
This has been added as part of 2.0.2. Thanks @Kleptobismol and @jairideout!
