### ISSUE TITLE
Metadata type inference problems

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/qiime2#404]
In some cases numbers are used as identifiers not as continuous variables, for example consider the mapping file here:

```python
with open('original.txt', 'w') as f:
    f.write('#SampleID\tsubject_id\n')
    f.write('s1\t00001\n')
    f.write('s2\t00002\n')
    f.write('s3\t10003\n')
```

Users might encounter a few problems with something like this:

- If this file is loaded and viewed as a DataFrame the data no longer matches the expectations i.e. if you try to find subject `'00001'` (as a string) you won't be able to, you will need to search for subject_id `1` (as a number).

```python
q2.Metadata.load('original.txt').to_dataframe()
```
![screen shot 2018-05-23 at 3 10 17 pm](https://user-images.githubusercontent.com/375307/40453854-6f7ae1b4-5e9b-11e8-8d15-cb0aec7cb85d.png)

- In a different situation, if you load this into a Metadata object and you save it back to a file, the leading zeroes will have been lost, for example:

```python
q2.Metadata.load('original.txt').save('saved.txt')
```
```bash
diff original.txt saved.txt
1,4c1,5
< #SampleID	subject_id
< s1	00001
< s2	00002
< s3	10003
---
> #SampleID	subject_id
> #q2:types	numeric
> s1	1
> s2	2
> s3	10003
```

**Comment by thermokarst** [comment]
Hey @ElDeveloper! I might be misreading this, but I think this is one of the main use-cases for the `#q2:types` [directive](https://docs.qiime2.org/2018.4/tutorials/metadata/#column-types). You can specify the type of the `subject_id` column as `categorical`, which will force the values in that column to be loaded as strings.

**Comment by ElDeveloper** [comment]
I see, thanks @thermokarst. Yes, that makes sense. To be fair I hadn't read that document in-depth and in a while.

To me it is surprising that the default behavior would do this, as I generally think of conservative defaults in these situations. The load->save problem is what seems to me the most unexpected.

Given that there had already been a fair amount of discussion around this topic, I think I'll close this issue, if anyone thinks this is still worth discussing feel free to re-open.
