### ISSUE TITLE
Dada2 error return code 1

### ISSUE THREAD

**Issue by khuch123** [qiime2/qiime2#413]
I have two samples paired end reads not yet joined
I ran dada2 denoise paired together on both of them
Then it gave error
I tried doing separate for each of my sample as per suggestions

But it still gave the same error

Attached are the comments

**Comment by khuch123** [comment]
Filtering
Learning error rates
Not all sequnces were the same length
Error rates could not be estimated
Incorrect number of subscripts on matrix
Execution halted

During handling above exception
Another exception occured

Plugin error from
Dada2
Return code 1

Please help at the earliest

**Comment by ebolyen** [comment]
Hi @khuch123, could you post your command and the full output to https://forum.qiime2.org instead of here? Thanks!
