### ISSUE TITLE
gneiss ilr-phylogenetic error

### ISSUE THREAD

**Issue by DKioroglou** [qiime2/qiime2#420]
Hello,

I tried to use the gneiss tool of qiime2 (v. 2018_11) with a phylogenetic tree.
I used the following command:
```
qiime gneiss ilr-phylogenetic \
	--i-table otu_table.qza \
	--i-tree rooted_tree.qza \
	--o-balances balances.qza \
	--o-hierarchy hierarchy.qza
``` 

The command finished without an error but when I tried to run the ols-regression I got the following error:
```
Plugin error from gneiss:

  'the label [y14] is not in the [index]'

Debug info has been saved to /tmp/qiime2-q2cli-err-c7n8hgv1.log
```

I looked at the log file and there was a KeyError raised.
I exported the files balances.qza and hierarchy.qza and in the file "**tree.nwk**" indeed there was a key "**y14**" but it was missing from the file "**feature-table.biom**".

I have run gneiss with the previous version of qiime2 without a phylogenetic tree, and there was no error.

Any idea of why I got this error?

Thank you in advance.

**Comment by thermokarst** [comment]
Hey there @DKioroglou! We actually don't provide user support here on GitHub (we tried to make that clear in our [issue templates](https://github.com/qiime2/qiime2/issues/new/choose), but if you have suggestions on how to make that more apparent please let us know!), but rather we encourage you to post this question over at the [QIIME 2 Forum](https://forum.qiime2.org) --- there are lots of eager folks ready to help you tackle this issue. Thanks!
