### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED for url -- Intermittent

### ISSUE THREAD

**Issue by laksyn** [qiime2/qiime2#427]
I am following instructions for "Natively installing QIIME 2" on a Linux system.  I've installed conda successfully and initiated the Qiime2 install.  Things look like they are going well but then some packages just don't download.  I've tried re-doing this multiple times (at night, weekends, early in the morning, etc..) and through different internet connections with the same results.  I looked through the qiime issues and tried things suggested there like turning off the firewall and also the SSL certificate check.  Still see these same packages not downloading.  Any suggestions?  

Below I have copied what I'm doing to show you what it looks like.  I've also attached a file with many more lines and re-attempts if you need more information.

Thank you for your help.

sh-4.2$ conda --version
conda 4.5.12
-bash-4.2$ wget https://data.qiime2.org/distro/core/qiime2-2018.11-py35-linux-conda.yml
--2019-01-03 16:03:16--  https://data.qiime2.org/distro/core/qiime2-2018.11-py35-linux-conda.yml
Resolving data.qiime2.org (data.qiime2.org)... 104.27.170.158, 104.27.171.158, 2606:4700:30::681b:aa9e, ...
Connecting to data.qiime2.org (data.qiime2.org)|104.27.170.158|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://raw.githubusercontent.com/qiime2/environment-files/master/2018.11/release/qiime2-2018.11-py35-linux-conda.yml [following]
--2019-01-03 16:03:16--  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.11/release/qiime2-2018.11-py35-linux-conda.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.32.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5663 (5.5K) [text/plain]
Saving to: ‘qiime2-2018.11-py35-linux-conda.yml’

100%[==============================================>] 5,663       --.-K/s   in 0s

2019-01-03 16:03:16 (36.0 MB/s) - ‘qiime2-2018.11-py35-linux-conda.yml’ saved [5663/5663]

-bash-4.2$ conda env create -n qiime2-2018.11 --file qiime2-2018.11-py35-linux-conda.yml
Solving environment: done

Downloading and Extracting Packages
pysocks-1.6.8        | 22 KB     | ################################################## | 100%
ipywidgets-7.4.2     | 92 KB     | ################################################# | 100%
r-nlme-3.1_137       | 2.2 MB    | ################################################  | 100%
arb-bio-tools-6.0.6  | 651 KB    |                                                                                                          |   0%
q2-taxa-2018.11.0    | 107 KB    |                                                                                                         |   0%
sortmerna-2.0        | 307 KB    |                                                                                                            |   0%
pandocfilters-1.4.2  | 9 KB      | ################################################# | 100%
testpath-0.3.1       | 89 KB     | ################################################## | 100%
....etc.  

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/arb-bio-tools-6.0.6-h5901010_5.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

[notes_qiime2_install.txt](https://github.com/qiime2/qiime2/files/2746911/notes_qiime2_install.txt)

**Comment by thermokarst** [comment]
Hey there @laksyn! This is almost certainly a firewall or other network-related issue --- for example, this link (https://conda.anaconda.org/bioconda/linux-64/arb-bio-tools-6.0.6-h5901010_5.tar.bz2) that you are reporting a connection error for is opening as expected here on my network. If you have further questions please find us on the QIIME 2 Forum - https://forum.qiime2.org, which is where we provided user support. Thanks!

**Comment by laksyn** [comment]
Thank you for the quick response.  Your help is greatly appreciated!

Maybe I'll try the docker install since it seems I am unable to get around the firewall issue.
