### ISSUE TITLE
Files generated in qiime2 can not be visualised???

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/qiime2#439]
Hi,
I generated working files (features table, rep-seq, tree,.....) as qza files in qiime2 few months ago. I have qiime2-2018.8 installed in my computer. Now I need to visualize rep-seq.qza file. It is generated successfully
qiime feature-table tabulate-seqs \--i-data rep_seq.qza \--o-visualization rep_seq.qzv
but when I visualize it
qiime tools view rep-seq.qzv

the browser opened with this message 
Your file was not found It may have been moved or deleted.
ERR_FILE_NOT_FOUND
May you please explain what is the issue?
Thanks
Eman

**Comment by emankhalaf** [comment]
I installed qiime2-2019.1 to use it instead of old releases, but when visualize other previously generated qzv files, I got the same error???

**Comment by thermokarst** [comment]
Hi @emankhalaf - can you please move this question to the [QIIME 2 Forum](https://forum.qiime2.org), that is where we provide end-user support. Thanks!
