### ISSUE TITLE
centralize functionality that is reused across many tests

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#44]
Specifically ``DummyType``, dummy workflows, etc. This is important for testing the basic functionality, as the actual types and workflows live in other repositories.

**Comment by gregcaporaso** [comment]
@jairideout, this one is done, right?

**Comment by jairideout** [comment]
Almost -- `qiime.core.testing` needs the dummy methods factored out of the unit tests. I may just take care of that during the method refactoring I'm working on.
