### ISSUE TITLE
Moving qiime2 anaconda.org channel to CDN

### ISSUE THREAD

**Issue by msarahan** [qiime2/qiime2#441]
**Improvement Description**
Greetings from the Anaconda team.  In an effort to reduce the load on our anaconda.org servers, we'd like to shift your channel over to our CDN.  Here are the implications:

1. Only the "main" label would be on the CDN.
2. Packages on the CDN will have a delay in availability from when they are uploaded, and when the next mirroring/indexing operation happens.  We would try for scheduling those every 20 minutes, but we can't make any sort of service level promise.
3. Packages on the CDN should have much faster download speeds, especially for people who are further from the US East Coast.
4. CDN-enabled channels will benefit from the new package format, while other anaconda.org channels will not, because anaconda.org does not support the new format yet.  This is more of a near-future benefit, rather than a current benefit.
5. You would gain the ability to hotfix your repodata to fix old packages with bad metadata.

Conda-forge has been on the CDN for several months now.  Things seem to be mostly OK for them.

**Questions**
Is this OK with your community?  If so, is there a convenient time for making the switch?  There were a few small hiccups with conda-forge, but it should be smoother now.  Nevertheless, planning for some small potential disruption would be wise.

**Comment by thermokarst** [comment]
Hey there @msarahan! Sorry for the traffic! We are certainly open to the CDN migration, but we are no longer actively using the `main` label (as of January 2019) for our QIIME 2 releases. We release each new version of QIIME 2 under its own specific release-label on the qiime2 channel, and we generally recommend that users install and work with whatever the "latest" release happens to be. The result there is that I _suspect_ that one label at a time will be responsible for the majority of traffic, and that label will change with each subsequent QIIME 2 release.

Long-term, our plan is to migrate these packages to bioconda, but we don't have an ETA on that. It looks like [you are planning](https://github.com/bioconda/bioconda-recipes/issues/13832) on migrating bioconda to the CDN, too.

Either way, you are totally welcome to move our `main` label over to the CDN, but we wouldn't want you to go through that effort for "nothing", in case our migration or label scheme impacts this decision. Keep us posted!

cc @ebolyen

**Comment by msarahan** [comment]
Thanks for the details on how your channel operates.  I don't think our CDN scheme will be useful right away, but if we need to reduce the server load further, we'll look into supporting your label scheme.

**Comment by qins** [comment]
@thermokarst Can you guys make latest version a copy to main?
Here in China, q2-* files download speed is 100 times slower than other package, yes, literally 100 times 😢 
![image](https://user-images.githubusercontent.com/3041080/68381802-6b463080-018d-11ea-9981-fc1db8741868.png)

**Comment by thermokarst** [comment]
Hi @qins! We have moved the latest release (2019.10) over to the `main` label - let us know how it goes for you! Thanks!
