### ISSUE TITLE
How to convert .csv to .fsn?

### ISSUE THREAD

**Issue by restivve** [qiime2/qiime2#448]
How can I convert my taxa file (in .csv format) to a .fsn file for use in Qiime2?

I'm trying to create a tree using a script like this: http://qiime.org/scripts/filter_tree.html, not sure if this script will work in Qiime2.

Victoria

**Comment by thermokarst** [comment]
Hi @restivve, please find us on the QIIME 2 Forum: https://forum.qiime2.org, that is where we provide official user support. Thanks!

**Comment by restivve** [comment]
I cannot log in there with my GitHub account, it says it won't allow a log in from my IP.

**Comment by thermokarst** [comment]
Please try again.
