### ISSUE TITLE
qiime2: I need each sample sequences from dada2. 

### ISSUE THREAD

**Issue by RChGO** [qiime2/qiime2#449]
Hello, I tried this command

qiime dada2 denoise-paired \
--i-demultiplexed-seqs ${infile} \
--o-table ${outdir}/table \
--o-representative-sequences ${outdir}/rep-seqs \
--o-denoising-stats ${outdir}/DADA2Stats \
--p-trim-left-f ${f_left} \
--p-trim-left-r ${r_left} \
--p-trunc-len-f ${f_len} \
--p-trunc-len-r ${r_len} \
--p-max-ee ${ov_max_mismatch} \
--p-min-fold-parent-over-abundance 2 \
--p-n-reads-learn 100000
--p-n-threads 28 \
--verbose"

and export table.qza:
sample-id       input   filtered        denoised        merged  non-chimeric
#q2:types       numeric numeric numeric numeric numeric
A0011   21937   21752   21752   21595   21201
A0012   26116   25923   25923   25634   25087

I need each sample sequences from dada2, e. g. 21201 sequences in sample A0001.

**Comment by RChGO** [comment]
Error corrected：

and export DADA2Stats.qza:
sample-id input filtered denoised merged non-chimeric
#q2:types numeric numeric numeric numeric numeric
A0011 21937 21752 21752 21595 21201
A0012 26116 25923 25923 25634 25087

I need each sample sequences from dada2, e. g. 21201 sequences in sample A0011.
Looking forward to help. Thanks!

**Comment by thermokarst** [comment]
Hi @RChGO, please find us on https://forum.qiime2.org --- that is where we provide official support for the QIIME 2 project. Thanks!

**Comment by RChGO** [comment]
> Hi @RChGO, please find us on https://forum.qiime2.org --- that is where we provide official support for the QIIME 2 project. Thanks!

The problem has already been solved. Thank you very much!
