### ISSUE TITLE
For better management multiple libraries

### ISSUE THREAD

**Issue by 444thLiao** [qiime2/qiime2#450]
**Improvement Description**
For better management libraries, I recommend one library named [`confapp`](https://github.com/UmSenhorQualquer/confapp). This is a package written by the author for better management his  [GUI project for video annotator](https://github.com/UmSenhorQualquer/pythonVideoAnnotator)

**Current Behavior**
Currently, I see inside the source code about the import of multiple libraries. Using string substitution to replace and import is not a good way to debug or seeking the relative function.

**Proposed Behavior**
Simply, I hope it won't raise any import error(which mean pycharm couldn't figure out where to find this library during inspections instead of running it ), or other IDE.

**References**
1. https://github.com/UmSenhorQualquer/confapp
2. https://github.com/UmSenhorQualquer/pythonVideoAnnotator

**Comment by thermokarst** [comment]
Hi @444thLiao - I am not quite sure I understand what you are proposing here (or even if there is anything wrong in the first place). Can you please expand on this issue a bit more for us? Thanks!
