### ISSUE TITLE
Combine CONTRIBUTING.md files

### ISSUE THREAD

**Issue by asoback** [qiime2/qiime2#452]
There are two contributing files, one on the main repository page, and another in the .github folder.

([https://github.com/qiime2/qiime2/blob/master/CONTRIBUTING.md](https://github.com/qiime2/qiime2/blob/master/CONTRIBUTING.md))  ([https://github.com/qiime2/qiime2/blob/master/.github/CONTRIBUTING.md](https://github.com/qiime2/qiime2/blob/master/.github/CONTRIBUTING.md))

 The second contains the same information as the first, and then some. That extra information is also valuable, and could live on the main repository page’s CONTRIBUTING.md file, which is much easier to find.

Additionally, the .github folder could be linked from the main CONTRIBUTING page, so its information is more readily accessible to newcomers, since the README and CONTRIBUTING pages are likely to be the first places they visit.

**Comment by thermokarst** [comment]
Hi @asoback!

> another in the .github folder.

This one is for the automatic GH integration [described here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).

Ideally we should just delete the `CONTRIBUTING.md` in the root of the repo, that is leftover from the old days :tm:

**Comment by asoback** [comment]
Ah that make sense, thanks!
