### ISSUE TITLE
Suggestions for a more beginners friendly README.md page

### ISSUE THREAD

**Issue by longhdo** [qiime2/qiime2#457]
Currently, the project README.md page contains only a link to the project official website which contains a hefty amount of information about the project. This current setup is great for developers with a natural "tinkering" mentality because they can dig into the official website and find as much information as they want to. However, this current setup may not be as helpful for beginners and developers with a more cautious, risk-averse mentality because they just want to find basic, relevant information about the project without spending too much time looking around in vast website.

So, I suggest the project README.md page to have a few new sections:

1. General section: contains a concise introduction about the project
2. Contributing section: contains a link to the CONTRIBUTING.md page plus some basic information about how to contribute to the project
3. Setup section: contains some basic instructions on how to properly set up the development environment for potential contributors
4. License section: brief licensing information about the project

**Comment by thermokarst** [comment]
Thanks @longhdo! @asoback put together a [PR](https://github.com/qiime2/qiime2/pull/451) a few weeks back that takes care of these concerns (I think). Thanks!
