### ISSUE TITLE
make types hashable

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#46]
This will be useful when we need to do type mapping, for example in the cli when we map QIIME types to click types.

**Comment by gregcaporaso** [comment]
This came up again today in the Qiita plugin - @ebolyen, could you do this as part of your work this week on the types?

**Comment by ebolyen** [comment]
:+1:

**Comment by gregcaporaso** [comment]
@ebolyen, this one is done, right?

**Comment by ebolyen** [comment]
Yep!
