### ISSUE TITLE
How can I display Newick tree at taxonomic level

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/qiime2#460]
Hi,
I need to export a newick tree displayed by genus level/any taxonomic level, so I could annotate and visualize the tree in other open sources.
The tree is displayed by OTUIDs, even after agglomeration (in R) still displayed by OTUID.
Is there any solution in qiime2?
Thanks

**Comment by thermokarst** [comment]
Hi @emankhalaf, unfortunately we are unable to provide user support here on GH --- please come find us on the QIIME 2 Forum: https://forum.qiime2.org, we can try and lend a hand there. Thanks!
