### ISSUE TITLE
Track memory usage in provenance

### ISSUE THREAD

**Issue by antgonza** [qiime2/qiime2#465]
**Addition Description**
Provenance in QIIME2 keeps track of execution time, it would be great if it also kept track of how much memory is used.

**Current Behavior**
Memory usage is not tracked.

**Proposed Behavior**
Track memory usage :)

**Comment by ebolyen** [comment]
I like this idea, but it's really hard to do as far as I know. Any thoughts on how to go about that?

**Comment by Oddant1** [comment]
@ebolyen this has only become more hairy now with parsl, so I'm going to say probably not.
