### ISSUE TITLE
Is it possible to use QIIME2 when there is no overlapping region? (EMP protocols)

### ISSUE THREAD

**Issue by natasharg** [qiime2/qiime2#469]
Hi -

I am going to be doing sequencing on several soil samples (16S, ITS) in the future following Earth Microbiome Project protocols. I currently have access to an Illumina iSeq 100 or MiSeq platforms but I realized that the iSeq only reads up to 2x150bp. For 16S and ITS, and including my attached adapters/primers, this would leave me with very little or no overlapping region between the forward and reverse reads. Would it still be possible for me to process that data accurately with QIIME2 or should I look for a way to read 2x250bp?

Thanks!

**Comment by thermokarst** [comment]
Hi @natasharg - can you please post this question to the QIIME 2 Forum - https://forum.qiime2.org? That is where we provide user support for QIIME 2 - thanks so much!
