### ISSUE TITLE
Dependencies installing qiime2-2018.11 and 2018.8 : "UnsatisfiableError"

### ISSUE THREAD

**Issue by Adrianzo** [qiime2/qiime2#470]
Hello, I'm unable to reinstall these environments that I've used in the past. I look forward doing it because some figures and results have already been submitted for publication. I only need to rework a part of the whole analysis pipeline.

In any of these past releases I get the same error. In the August release the error was about `r-pillar=1.2.2` package. I will copy the error I get trying to create an environment using the November release `YAML`:

```
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - freetype=2.9.1
  - pcre=8.41
  - q2-dada2=2018.11.0
Use "conda search <package> --info" to see the dependencies for each package.
```

This possibly affects another past releases. Isn't possible to install them? If that's the situation the problem is of big concern around reproducibility of our analysis pipelines. I guess there's some piece of the puzzle that I'm not seeing. Any help would be appreciated.

In case you are wondering, this is the output I get after running `conda info`:

```
     active environment : base
    active env location : /opt/anaconda
            shell level : 1
       user config file : /home/username/.condarc
 populated config files : /home/username/.condarc
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /opt/anaconda  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /home/username/.conda/pkgs
       envs directories : /home/username/.conda/envs
                          /opt/anaconda/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Linux/5.1.16.a-1-hardened arch/2019.1.20 glibc/2.29
                UID:GID : 1000:985
             netrc file : None
           offline mode : False
```

Cheers!

**Comment by thermokarst** [comment]
Hi @Adrianzo - the packages you appear to be having issues with are third-party packages that we don't have control over, my guess is they have been taken down or replaced. If you need access to old releases and conda isn't cutting it for you, then I encourage you to take a look at [our VM offerings](https://docs.qiime2.org/2018.8/install/virtual/) --- these should all have the envs you are looking for. Thanks!

**Comment by Adrianzo** [comment]
Thanks! the docker images will suit my needs.

By the way, I believe this issue was related with bioconda changing their channel priorities in september 2018: https://github.com/bioconda/bioconda-utils/releases/tag/v0.14.5
