### ISSUE TITLE
Artifact Level Caching

### ISSUE THREAD

**Issue by dhakim87** [qiime2/qiime2#480]
**Addition Description**
Since the artifacts contain provenance, one could compute whether an existing artifact on disk is the direct result of running a particular function with my current set of arguments.  A change in the API methods that allows an optional cache-artifact or output-artifact would allow each method to check whether an already stored artifact would be reusable in the current state.  It could also guarantee the artifacts are saved, which is one less method call for the end user, and feels like the intended usage pattern.  

**Current Behavior**
Any caching of long running operations is left to the end user.  

**Proposed Behavior**
The library provides artifact level caching, such that any function that generates an artifact first checks if that artifact exists, is equivalent to what the function would return when run on the current inputs, and if so, uses the cached version rather than recomputing.  

**Comments**
When developing with Jupyter Notebooks, I generally end up with a cell that takes a huge amount of time to run (e.g. qiime2.plugins.diversity.actions.core_metrics_phylogenetic).  The next line afterwards is always to save the long running computation results to disk as one or more artifacts.  But the next time I run the code, I have no concise way to check if the artifact exists, check if it is correct for the given arguments, check that the version of software that generated it is a perfect match, etc.  Ideally, it would be simple for me as an end user to either restore an existing artifact OR run the qiime2 function as applicable, but the code required within the notebook to allow that is non trivial.

**Comment by ebolyen** [comment]
I've been frustrated by this as well before. The machinery for this is also needed for "resumable" pipelines, which has been on my todo list for a long time now. I'm curious what the API would ultimately look like for this.

I can imagine perhaps a context manager like:
```python
with qiime2.cache('~/somewhere/convenient/'):
    table, = qiime2.plugins.feature_table.actions.filter_features(...)
```

Which would in principle inject some middleware behind the scenes to auto-return matching artifacts?

**Comment by Oddant1** [comment]
We actually do this now with pipeline resumption
