### ISSUE TITLE
The file path to a `BoundFile` object should be easily accessible

### ISSUE THREAD

**Issue by Oddant1** [qiime2/qiime2#481]
**Improvement Description**
Make `BoundFile` filepaths easily accessible.

**Current Behavior**
Their doesn't seem to be any easy way to access the path to a `BoundFile` object. Their repr just shows them as a Python object, and their `name` attribute isn't a filepath either.

**Proposed Behavior**
Create an easy way to access the path to a `BoundFile`

**Question**
1. Are there any technical limitations restricting the ability to make this a thing?

**Comments**
1. Probably just do this via the exposure of a new `path` parameter.

**Comment by thermokarst** [comment]
Is this issue confusing `BoundFile` with `TextFileFormat`/`BinaryFileFormat`? `BoundFile` already _does_ have a `view` method, while the unbound formats (`TextFileFormat` and `BinaryFileFormat`) don't. That means you can't call `view` on a `TextFileFormat` _unless_ it is a member of a `DirectoryFormat` (and thus, is a `BoundFile`).

**Comment by thermokarst** [comment]
This functionality _does_ exist, currently - does this meet your needs, @Oddant1?

Using [this Artifact](https://docs.qiime2.org/2019.7/data/tutorials/moving-pictures/demux.qza) as input.

```python
import qiime2
from q2_types.per_sample_sequences import SingleLanePerSampleSingleEndFastqDirFmt

x = qiime2.Artifact.load('demux.qza').view(SingleLanePerSampleSingleEndFastqDirFmt)
print(x.manifest.path_maker())
```
Which returns:

```
/tmp/matthew/qiime2-archive-owop1d70/4dbc0b6f-0b9e-4449-a350-c415f3e30be7/data/MANIFEST
```

**Comment by Oddant1** [comment]
@thermokarst I could have sworn we talked about the `path_maker` and it did something else, but that being the case I'll get rid of this.
