### ISSUE TITLE
document plugin requirements and recommendations

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#5]
This will include things like the structure of a plugin, requirements for official QIIME 2 plugins (CI testing and coverage, flake8, etc), and recommendations for unofficial plugins.

**Comment by souravsingh** [comment]
@gregcaporaso I would like to work on the issue.

**Comment by jairideout** [comment]
Closing since we have [basic plugin developer documentation](https://docs.qiime2.org/2.0.6/plugins/developing/) and `qiime dev plugin-init` (plugin cookiecutter).
