### ISSUE TITLE
Cannot find 'assign_taxonomy.py'

### ISSUE THREAD

**Issue by bitcometz** [qiime2/qiime2#501]
hello, I install qiime2 throught conda:

**conda env create -n qiime2-2019.7 --file qiime2-2019.7-py36-linux-conda.yml**
**source activate qiime2-2019.7**

I want to use the 'assign_taxonomy.py' but I cannot find it in the 
qiime enviroment.
Where can I find this script?

Thanks!!!!

**Comment by nbokulich** [comment]
assign_taxonomy.py is not a part of QIIME 2, it is a script from qiime 1, hence why it was not installed. 

In the future, please use the [QIIME 2 forum](https://forum.qiime2.org/) for all support questions. Thanks!
