### ISSUE TITLE
Gracefully fall back on tzlocal failures

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#510]
**Improvement Description**
Currently, if a deployment environment isn't [configured correctly](https://github.com/regebro/tzlocal/issues/79), tzlocal will fail with a message like:

```python
ValueError: Timezone offset does not match system offset: 0 != -25200. Please, check your config files.
```

The timezone information is potentially useful for decentralized provenance (at least in theory), but not strictly necessary, so perhaps a solution is to fall back to UTC if tzlocal isn't able to initialize properly.

**Alternatives**
1. Timezone info could be scrapped.
2. Identify an alternative to tzlocal

**References**
1. https://forum.qiime2.org/t/error-while-running-qiime2-valueerror-timezone-offset-does-not-match-system-offset-0-25200-please-check-your-config-files/11418
2. https://github.com/qiime2/qiime2/issues/493
3. https://github.com/nf-core/ampliseq/issues/114

**Comment by thermokarst** [comment]
Turns out tzlocal already does fall back to UTC, but, only when _no timezone info is present_ on the system. Otherwise, the error reported above is raised specifically when the host config is in an inconsistent state.

**Comment by ebolyen** [comment]
It should be really easy to just back out of the tzlocal logic if we see that ValueError. I kind of wish they had a custom baseclass for that exception though.

So I think that would be my vote for now, use it if it is consistent, otherwise ignore it entirely.

**Comment by thermokarst** [comment]
Closed in #513.

**Comment by rsettlage** [comment]
Hi,
I have a few users encountering this issue.  Is there a timeline for pushing 2020.2?  Or should I ask them to install from the git repo?
Thanks,
Bob

**Comment by thermokarst** [comment]
Hi @rsettlage!

>  Is there a timeline for pushing 2020.2?

2020.2 release plans can be found here:

- https://forum.qiime2.org/t/preview-qiime-2-2020-2-development-changelog/12328/
- https://github.com/orgs/qiime2/projects/18

> I have a few users encountering this issue.

One immediate solution is that they can attempt to resolve the misconfigured environment. tzlocal is raising this warning because it has detected _multiple conflicting_ timezone configurations.
