### ISSUE TITLE
Timestamps for artifacts

### ISSUE THREAD

**Issue by sjanssen2** [qiime2/qiime2#521]
I thought completed an analysis some years ago. Of course paper submission got delayed and I am now asked to re-do some parts with a few additional samples. Thus, I'd like to know if I produced certain artifacts two years ago or three month ago - but I don't see an easy way to obtain this information.

Wouldn't it be great if Qiita could somehow indicate the time stamp for an artifact?

**Comment by ebolyen** [comment]
Hey @sjanssen2, we do in fact have this info in provenance! Just click on an action (box) to see those details on the top.

![image](https://user-images.githubusercontent.com/3976804/74172464-8772c700-4bed-11ea-81b8-0e04c39b8d7d.png)

**Comment by sjanssen2** [comment]
@ebolyen stupid me, I wanted to open this issue for qiita not for qiime2. That happens if you relay on autocompletion in your browser. Sorry.
And yes, I am aware and love all the provenance information!!

**Comment by antgonza** [comment]
For completeness, this is the issue in qiita: https://github.com/biocore/qiita/issues/2974.
