### ISSUE TITLE
decorated Actions with default params fail

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/qiime2#524]
**Bug Description**
Actions that have default parameters fail with `KeyError: 'name_of_first_default_param'` if those Actions have had decorators functions applied to them.

This is caused by a framework bug, where default arguments are unintentionally stripped (in `Action._rewrite_wrapper_signature()`?), causing `Action.bound_callable()` to pass truncated argument lists to `self.signature.check_types()`. `check_types()` fails while attempting to access kwargs that still exist in `self.signature.order_items` which have been stripped from the kwargs it received.

**Steps to reproduce the behavior**
1. Check out the following branches in a dev environment: 
https://github.com/ChrisKeefe/q2-diversity/tree/divLibWiring
https://github.com/ChrisKeefe/q2-diversity-lib/tree/bDiv
2. `make dev` (it _may_ be necessary to do so in both repos?)
3. navigate to q2-diversity, and `make test`

This should wire `q2-diversity` to use decorated Actions that are implemented in `q2-diversity-lib`, and raise relevant errors during testing.

Alternately, you could write a simple decorator function, apply it to an existing Action in any repo _that has one or more default parameters_, and test. If results vary, please let us know below.

**Expected behavior**
`KeyError: 'name_of_first_default_param' will be raised when calling decorated Actions with default parameters.

**Computation Environment**
- OS: LinuxMint 19.2, likely all others.
- QIIME 2 2019.10

**Questions**
1. Is it best for us to generate a new signature, rather than continuing to abuse the decorator library in manipulating wrapper signatures?

**References**

1. [decorator](https://github.com/micheles/decorator/blob/master/src/decorator.py) library
2. [check_types](https://github.com/qiime2/qiime2/blob/90f7bbf7c9bce673c6c2809f6ddfcd56ca3eee4c/qiime2/core/type/signature.py#L323)
3. [bound_callable](https://github.com/qiime2/qiime2/blob/90f7bbf7c9bce673c6c2809f6ddfcd56ca3eee4c/qiime2/sdk/action.py#L185)
4. [rewrite_wrapper_signature](https://github.com/qiime2/qiime2/blob/90f7bbf7c9bce673c6c2809f6ddfcd56ca3eee4c/qiime2/sdk/action.py#L299)
5.  Branches where the bug first materialized: 
     - https://github.com/ChrisKeefe/q2-diversity/tree/divLibWiring
     - https://github.com/ChrisKeefe/q2-diversity-lib/tree/bDiv

**Comment by thermokarst** [comment]
I just tried reproducing this error by creating a simple wrapper in q2-metadata, and was unable to reproduce this error. The modified code (https://github.com/qiime2/q2-metadata/blob/master/q2_metadata/_tabulate.py):

```python
import functools
def identity_decorator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)
    return wrapper


@identity_decorator
def tabulate(output_dir: str, input: qiime2.Metadata,
             page_size: int = 100) -> None:
 ...
```

Provenance for the returned viz looks good, too:

![Screen Shot 2020-05-08 at 5 14 37 PM](https://user-images.githubusercontent.com/274668/81458478-6e77a480-914f-11ea-9530-8f9b37d073a6.png)

In particular, the `page_size` param appears to have been initialized (and passed along) as expected.

---

I _was_ able to reproduce the q2-diversity && q2-diversity-lib errors you reported, however. This got me thinking, well, what might be different about these two cases. So I found a way to make my example above fail. **Wrap the viz in a pipeline**

```python
def pipeline(ctx, input):
    tabulate = ctx.get_action('metadata', 'tabulate')
    return tabulate(input=input)
```

```bash
qiime metadata pipeline --m-input-file ../data/moving-pictures/sample-metadata.tsv --o-viz ~/Desktop/deleteme.qzv --verbose                bDiv 1a73615 ✗
Traceback (most recent call last):
  File "/Users/matthew/projects/qiime2/q2cli/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-430>", line 2, in pipeline
  File "/Users/matthew/projects/qiime2/qiime2/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/Users/matthew/projects/qiime2/qiime2/qiime2/sdk/action.py", line 484, in _callable_executor_
    outputs = self._callable(scope.ctx, **view_args)
  File "/Users/matthew/projects/qiime2/q2-metadata/q2_metadata/_tabulate.py", line 60, in pipeline
    viz, = tabulate(input=input)
  File "<decorator-gen-516>", line 2, in tabulate
  File "/Users/matthew/projects/qiime2/qiime2/qiime2/sdk/action.py", line 208, in bound_callable
    self.signature.check_types(**user_input)
  File "/Users/matthew/projects/qiime2/qiime2/qiime2/core/type/signature.py", line 327, in check_types
    parameter = kwargs[name]
KeyError: 'page_size'

Plugin error from metadata:

  'page_size'

See above for debug info.
```

I haven't had a chance to look #531, so I'm not sure if you've already looked into this, but I am wondering if the framework can generally handle decorated actions just fine, but rather, `Pipeline` is somehow mangling the action's signature. I haven't looked at the `Pipeline` machinery, but I wonder if we just need to `unwrap` the action somewhere.

This issue comment is mostly just notes so that I can pick this back up again later.

**Comment by thermokarst** [comment]
Okay, a few more notes: I started looking at the `decorator` library (used in `action.py`), which  has a pretty specific mission, primarily for preserving wrapped function signatures.

By replacing my stdlib `functools.wraps` with

```python
import decorator
@decorator.decorator
def identity2_decorator(func, *args, **kwargs):
    return func(*args, **kwargs)
```

my pipeline works, default params and all. I wonder if the framework even needs to do anything different, since it looks like the wrapped function.

So, backing up to q2-div-lib, one solution that "works" for me (it unblocks the missing default params issue, but I think the q2-div tests will need to be updated to work correctly with these tweaks):

```diff
diff --git a/q2_diversity_lib/_util.py b/q2_diversity_lib/_util.py
index ca55524..ee2642f 100644
--- a/q2_diversity_lib/_util.py
+++ b/q2_diversity_lib/_util.py
@@ -7,10 +7,10 @@
 # ----------------------------------------------------------------------------
 
 import numpy as np
-from functools import wraps
 from inspect import signature
 import psutil
 from biom import load_table
+import decorator
 
 
 def _drop_undefined_samples(counts: np.ndarray, sample_ids: np.ndarray,
@@ -24,57 +24,51 @@ def _drop_undefined_samples(counts: np.ndarray, sample_ids: np.ndarray,
     return (filtered_counts, filtered_sample_ids)
 
 
-def _disallow_empty_tables_passed_object(some_function):
-    @wraps(some_function)
-    def wrapper(*args, **kwargs):
-        try:
-            bound_signature = signature(some_function).bind(*args, **kwargs)
-            table = bound_signature.arguments['table']
-        except KeyError as ex:
-            raise TypeError("The wrapped function has no parameter "
-                            + str(ex) + ".")
-        if table.is_empty():
-            raise ValueError("The provided table object is empty")
-        return some_function(*args, **kwargs)
-    return wrapper
+@decorator.decorator
+def _disallow_empty_tables_passed_object(some_function, *args, **kwargs):
+    try:
+        bound_signature = signature(some_function).bind(*args, **kwargs)
+        table = bound_signature.arguments['table']
+    except KeyError as ex:
+        raise TypeError("The wrapped function has no parameter "
+                        + str(ex) + ".")
+    if table.is_empty():
+        raise ValueError("The provided table object is empty")
+    return some_function(*args, **kwargs)
 
 
-def _disallow_empty_tables_passed_filepath(some_function):
-    @wraps(some_function)
-    def wrapper(*args, **kwargs):
-        try:
-            bound_signature = signature(some_function).bind(*args, **kwargs)
-            table = bound_signature.arguments['table']
-        except KeyError as ex:
-            raise TypeError("The wrapped function has no parameter "
-                            + str(ex) + ".")
-        biom_table = load_table(table)
-        if biom_table.is_empty():
-            raise ValueError("The provided table object is empty")
-        return some_function(*args, **kwargs)
-    return wrapper
+@decorator.decorator
+def _disallow_empty_tables_passed_filepath(some_function, *args, **kwargs):
+    try:
+        bound_signature = signature(some_function).bind(*args, **kwargs)
+        table = bound_signature.arguments['table']
+    except KeyError as ex:
+        raise TypeError("The wrapped function has no parameter "
+                        + str(ex) + ".")
+    biom_table = load_table(table)
+    if biom_table.is_empty():
+        raise ValueError("The provided table object is empty")
+    return some_function(*args, **kwargs)
 
 
-def _safely_constrain_n_jobs(some_function):
-    @wraps(some_function)
-    def wrapper(*args, **kwargs):
-        # If `Process.cpu_affinity` unavailable on system, fall back
-        # https://psutil.readthedocs.io/en/latest/index.html#psutil.cpu_count
-        bound_signature = signature(some_function).bind(*args, **kwargs)
-        bound_signature.apply_defaults()
-        try:
-            n_jobs = bound_signature.arguments['n_jobs']
-        except KeyError:
-            raise TypeError("The _safely_constrain_n_jobs decorator may not be"
-                            " applied to callables without 'n_jobs' parameter")
-        try:
-            cpus = len(psutil.Process().cpu_affinity())
-        except AttributeError:
-            cpus = psutil.cpu_count(logical=False)
-        if n_jobs > cpus:
-            raise ValueError('The value of n_jobs cannot exceed the'
-                             ' number of processors (%d) available in'
-                             ' this system.' % cpus)
+@decorator.decorator
+def _safely_constrain_n_jobs(some_function, *args, **kwargs):
+    # If `Process.cpu_affinity` unavailable on system, fall back
+    # https://psutil.readthedocs.io/en/latest/index.html#psutil.cpu_count
+    bound_signature = signature(some_function).bind(*args, **kwargs)
+    bound_signature.apply_defaults()
+    try:
+        n_jobs = bound_signature.arguments['n_jobs']
+    except KeyError:
+        raise TypeError("The _safely_constrain_n_jobs decorator may not be"
+                        " applied to callables without 'n_jobs' parameter")
+    try:
+        cpus = len(psutil.Process().cpu_affinity())
+    except AttributeError:
+        cpus = psutil.cpu_count(logical=False)
+    if n_jobs > cpus:
+        raise ValueError('The value of n_jobs cannot exceed the'
+                         ' number of processors (%d) available in'
+                         ' this system.' % cpus)
 
-        return some_function(*args, **kwargs)
-    return wrapper
+    return some_function(*args, **kwargs)
```

that diff looks like a lot, but its mostly just de-indenting code. Give that a shot, @ChrisKeefe, this might get you moving forward again, for now.

**Comment by thermokarst** [comment]
My current plan is to close out this issue, since we appear to have settled the signature issues in q2-diversity-lib's decorators. Will wait to see how div-lib shakes out before closing, though.

**Comment by ChrisKeefe** [comment]
I think we're ok to close this now, @thermokarst. :smiley:
