### ISSUE TITLE
investigate snakemake as pipeline backend

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#54]
**Improvement Description**
It has a simple, declarative file format, supports cluster execution, and connects to a variety of resources out of the box (including Amazon S3, Google Storage, Dropbox, FTP, SFTP). The snakemake devs are working on adding cloud support. It's written in Python 3, and was initially developed for bioinformatics applications (so there's _a lot_ of real-world examples and publications using it). The snakemake devs are bioconda devs, so it's available via bioconda. This looks like a very, very sane bioinformatics library that could be used outright, or extended, to provide true DAG workflow/pipeline specification and execution in QIIME 2. This is definitely worth investigating further!

**Comments**
@bhillmann suggested [snakemake](https://bitbucket.org/snakemake/snakemake/wiki/Home) as a workflow/pipeline management engine. @ebolyen and I briefly looked into it and are amazed. A few of the highlights (thanks @ebolyen!):

**Comment by ebolyen** [comment]
Also check out [this issue!](https://bitbucket.org/snakemake/snakemake/issues/277/snakemake-in-the-cloud) They are thinking about extending this to execute on remote machines and finding subdags for efficient host execution.

**Comment by gregcaporaso** [comment]
This sounds great - thanks @bhillmann, and thanks for looking into it @jairideout and @ebolyen!

**Comment by ebolyen** [comment]
Tagging @johanneskoester (author of snakemake and [rust-bio!](https://github.com/rust-bio/rust-bio))

**Comment by johanneskoester** [comment]
Thanks for considering Snakemake! It would be great to see QIIME using it! Please let me know if I can help in any way.

**Comment by gregcaporaso** [comment]
We went in a different direction and this is no longer relevant.
