### ISSUE TITLE
Clean up usage module

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#544]
**Bug Description**
Some usage methods have type annotations, some don't. Nothing has docstrings. `_init_data_collection_` appears to have an errant `*` on the records attr (although I might need to look more closely at this). In general this module could use a nice tidying-up.

**Comment by andrewsanchez** [comment]
> `_init_data_collection_` appears to have an errant `*` on the records attr (although I might need to look more closely at this).

Why do you suspect it's errant?  I thought it needed to be `*records` and is being used that way: 

https://github.com/qiime2/qiime2/blob/master/qiime2/core/testing/examples.py#L174-L182

```python
def variadic_input_simple(use):
    ints_a = use.init_data('ints_a', ints1_factory)
    ints_b = use.init_data('ints_b', ints2_factory)
    ints = use.init_data_collection('ints', list, ints_a, ints_b)


    single_int1 = use.init_data('single_int1', single_int1_factory)
    single_int2 = use.init_data('single_int2', single_int2_factory)
    int_set = use.init_data_collection('int_set', set, single_int1,
                                       single_int2)
```

**Comment by thermokarst** [comment]
> Why do you suspect it's errant?

Check out how `merge_metadata/_merge_metadata_` works - we want the `*records` in the public API (`init_data_collection`), but we want a single param `records` on the SDK-side of the API (`_init_data_collection_`)
