### ISSUE TITLE
Job object is not accessible through the use of SubprocessExecutor 

### ISSUE THREAD

**Issue by jakereps** [qiime2/qiime2#55]
`.sdk.execution.SubprocessExecutor` creates a `.sdk.job.Job`, and writes the code to a file to be ran, but doesn't allow access to the object information itself. This was noticed while trying to use the `Job.uuid` as the identifier for tracking the current processes being ran by qiime-studio, and realizing that only the `Future` object was being returned.

Found while working on [PR#32 in qiime-studio](/qiime2/qiime-studio/pull/32#discussion-diff-67222461)

**Comment by jairideout** [comment]
I'll take this one, it depends on the workflow inversion/refactoring I'm starting soon. `Job` should probably know how to execute its code and `SubprocessExecutor` can be removed.

**Comment by jairideout** [comment]
@jakereps, `SubprocessExecutor.__call__` now returns a tuple `(future, job)`, let me know if you run into any issues using it in the studio!
