### ISSUE TITLE
Experienced some problems in qiime fragment-insertion sepp 

### ISSUE THREAD

**Issue by aiguoguo1** [qiime2/qiime2#557]
when run "qiime fragment-insertion sepp --i-representative-sequences rep-seqs.qza --i-reference-database sepp-refs-gg-13-8.qza --o-tree ./tree.qza --o-placements ./tree_placements.qza"

 Some problems occured and returned"returned non-zero exit status 1"

How to solve this problem?

**Comment by nbokulich** [comment]
Hi @aiguoguo1 ,
Please see the QIIME 2 forum for user support and troubleshooting: https://forum.qiime2.org/
