### ISSUE TITLE
Metadata categorical types are bit too strict

### ISSUE THREAD

**Issue by mortonjt** [qiime2/qiime2#568]
**Addition Description**

Right now if you have a column of unique ids (i.e. host_subject_id) that are integer valued but if you want to pass it in as a categorical type, qiime2 will throw an error that looks like below

**Current Behavior**
```
 (2/2) Invalid value for '--m-replicates-file': Metadata column is of type
  'numeric', but expected Categorical.
```

**Proposed Behavior**
A better way to handle this is if the metadata column is expected to be categorical, then it should be forced to be categorical by converting all of the values in the column to strings.

**Comments**
This problem isn't unique to the [q2-batch](https://github.com/mortonjt/q2-batch/blob/main/q2_batch/plugin_setup.py#L25) that I'm putting together, but really all of the differential abundance tools that use the metadata column paradigm. We're planning on automating these types of diff abundance analysis on dozens of studies that use the qiita standards for metadata; where these sorts of errors induce additional user / developer burden.  Having more relaxed handling of categorical types would significantly ease user burden moving forward.

EDIT:
The current solution to this problem is to directly modify the categorical columns.  My current solution is to append 'X' in front of the variables via
```python
import argparse
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument(
    '--metadata-file', help='Metadata file', required=True)
parser.add_argument(
    '--categorical-column', help='Categorical column', required=True)
parser.add_argument(
    '--output-file', help='Output metadata file', required=True)

args = parser.parse_args()

md = pd.read_table(args.metadata_file, index_col=0)
md[args.categorical_column] = md[args.categorical_column].apply(lambda x: 'X' + str(x))
md.to_csv(args.output_file, sep='\t')
```

Of course, it would be more elegant to have the type casting handled internally in qiime2 metadata.  If we agree that this is useful, I'll be happy to push in a pull request.

**Comment by antgonza** [comment]
Ha! We are actually discussing this same "feature" in Qiita, for reference: https://github.com/qiita-spots/qiita/issues/2947. To be fair, I completely forgot about the numeric host_subject_ids or sample_name, which happens ofter.

Something I considered to fix in Qiita was to add a GUI for the sample information file where you can change the `#q2:types` of the columns (perhaps by default categorical). Extra from development it has other internal management issues (saving backups, etc).

Anyway, thought it might be beneficial to link both issues.

**Comment by ElDeveloper** [comment]
What about two options that are added to any plugin with a `Metadata` parameter. Namely `--p-as-categorical` and `--p-as-numeric` this way users can have a say on how metadata is interpreted depending on the plugin. For example:

```bash
qiime differential-abundance flipacoin \
--i-feature-table table.qza \
--m-mapping-file mapping-file.tsv \
--p-formula Treatment+Age_In_Years+Cage \
--m-as-numeric Age_In_Years \
--m-as-categorical Cage \
--m-as-categorical Treatment \
--o-differentials diffs.qza
```

In this case you can picture all these variables having numeric values (`Cage` being a numeric identifier and `Treatment` being a zero or a one). I know something like this would get complicated for things like the Python interface. But what I like about this approach is that type-inferences would be visible in the provenance information.

-----

Clearly this is a topic of interest to a lot of us. 👍

**Comment by antgonza** [comment]
I like @ElDeveloper idea. Now, how can we expand it to commands where you don't list the columns of interest in the call, like alpha group significance ...

**Comment by thermokarst** [comment]
> But what I like about this approach is that type-inferences would be visible in the provenance information.

I think that's exactly what the typed-columns I shared above dose - provenance captures the metadata provided, including the type annotations provided by the user.

> Clearly this is a topic of interest to a lot of us.

For sure! Like I said, I am interested in @mortonjt's initial suggestion! I wanted to share the current column typing spec, because it looked like @mortonjt wasn't aware that users can directly control how that inference is performed, right now.

**Comment by ElDeveloper** [comment]
> I think that's exactly what the typed-columns I shared above does - provenance captures the metadata provided, including the type annotations provided by the user.

🤯 wait what? That's cool, I didn't know about this feature. Where is that info displayed/registered though? For example in the provenance for [this](https://view.qiime2.org/provenance/?src=https%3A%2F%2Fdocs.qiime2.org%2F2020.11%2Fdata%2Ftutorials%2Flongitudinal%2Fvolatility.qzv) artifact I only see the variable names not the types.

**Comment by thermokarst** [comment]
Unfortunately it isn't rendered anywhere in q2view (yet!), but you can grab it out of the archive:

```bash
wget https://docs.qiime2.org/2021.2/data/tutorials/pd-mice/metadata.qzv
qiime tools extract --input-path metadata.qzv --output-path metadata
head metadata/4dbb2457-180f-40f0-9a8d-e37538c48b3b/provenance/action/input.tsv
```

This metadata is tracked ancestrally, too, so you'll have access to it (via the provenance dir) in downstream outputs, too.

**Comment by mortonjt** [comment]
I was aware of the typed columns; I think that was a great addition!
One of the reasons why I raised this was because adding typed columns was looking tedious (we've got many metadata files that we're juggling).  

Since this appears to be a recurring use case, I wonder if we could make this process even more straightforward by forcing the types. If the input type `MetadataColumn[Categorical]` is already specified, then it could be useful if this typing could be automatically enforced on the metadata.

**Comment by thermokarst** [comment]
> One of the reasons why I raised this was because adding typed columns was looking tedious (we've got many metadata files that we're juggling).

Personally I would go for the option that doesn't mutate the input data!

> I wonder if we could make this process even more straightforward by forcing the types

I think there is certainly merit for making this work this way in the case of `MetadataColumn[Categorical]` - any value type can be represented as categorical data (I think). I'm less certain about the `MetadataColumn[Numerical]` case, or even future as-yet-written column types, though.

Question - do you think a utility for this casting would get you what you need? For example, we could expose parameters in q2-metadata's `tabulate` viz that would accept an optional list of "columns to make categorical" or "columns to make numerical" - then that metadata could be yanked out of the viz/provenance and used downstream. Just spitballing ideas here. Or we could make this util a built-in, so an interface like q2cli could have a `qiime tools cast-metadata` command, or something like it.

**Comment by ElDeveloper** [comment]
> This metadata is tracked ancestrally, too, so you'll have access to it (via the provenance dir) in downstream outputs, too.

So cool! This seems like an opportunity for expanding on q2view's capabilities.

**Comment by ElDeveloper** [comment]
> I think there is certainly merit for making this work this way in the case of MetadataColumn[Categorical] - any value type can be represented as categorical data (I think). I'm less certain about the MetadataColumn[Numerical] case, or even future as-yet-written column types, though.

Come to think about it this would make more sense than adding new options. Some error handling would need to be included to raise errors when the data can't be cast to numeric, or when all the categorical values are unique, etc. 👍

**Comment by mortonjt** [comment]
Errors would be great for the `MetadataColumn[Numerical]` use case; we've had users that run into non-intuitive errors when running Songbird on continuously valued data.  The worst is when there is a silent error, and the program will process numerical data, but treat it as categorical.

**Comment by thermokarst** [comment]
> we've had users that run into non-intuitive errors when running Songbird on continuously valued data

Can you point us at some issues or discussions somewhere? Is this related to QIIME 2, or to songbird? I cursory glance in the songbird code looks like you don't really use QIIME 2 metadata in any of the Actions defined there, instead it looks like `Metadata` is converted to `pd.Dataframe` early and often - at that point I'm not too sure what we can do for yah - but there are some APIs on metadata that might make your life a little bit easier - we should chat more about improvements that could be made to Songbird using the _existing_ API!

> The worst is when there is a silent error, and the program will process numerical data, but treat it as categorical.

Interesting - this is the first report of a silent metadata error I have heard - that must be a frustrating situation. Please share some more specifics so that we can help you get to the bottom of it.

**Comment by mortonjt** [comment]
Not a problem.  Below is an example of a silent user error with continuous variables (I've received this question a number of times over email as well).

https://github.com/biocore/songbird/issues/151

I agree, it would be great if we could use the Metadata API; but I was under the impression that the Metadata API does not offer support for Patsy formula formatting (I see that there is a bit of overhead code in [q2-longitudinal](https://github.com/qiime2/q2-longitudinal/blob/d01e53ebaf85ebf77981251ab9eebef12587c267/q2_longitudinal/_utilities.py#L840) to handle this). Would love to follow up discussions on this; perhaps its worthwhile to raise a separate issue for patsy support?

**Comment by mortonjt** [comment]
Hi @thermokarst I've opened up a pull request.  

Yes, your comment regarding the header would probably help - but in all honestly, there are too many competing standards for metadata file types.  That change would break all of my code that relies on qiita metadata files for instance.

I've opened up a WIP pull request at https://github.com/qiime2/qiime2/pull/588
I think this minor change will be advantageous for q2, since this is a common convention in the ML community anyways.

**Comment by thermokarst** [comment]
Thanks for linking to that issue @mortonjt - this looks like a case where perhaps a second-look at the docs would be helpful: https://docs.qiime2.org/2021.4/tutorials/metadata/#number-formatting

> Common representations of not a number (e.g. NaN, nan) or infinity (e.g. inf, -Infinity) are not supported. Use an empty cell for missing data (e.g. instead of NaN). Infinity is not supported at this time in QIIME 2 metadata files.

I don't think the PR you've opened will solve this problem. Do you still think that this requires a change to the metadata spec in QIIME 2 after re-reading the metadata spec?

**Comment by mortonjt** [comment]
Hi @thermokarst , thank you for following up.  The songbird issue is a separate one regarding numerical types rather than categorical. The PR I've opened allows for integer-valued columns to be used as categorical variables.   I'm currently running into this issue with q2-sample-classifier as well - should I raise an issue there? CC @nbokulich

Here's another question, if one type under the q2:types directive is specified, do they all need to be specified?
One of the reasons why I haven't jumped on this train yet is because many of the metadata files that I'm dealing with have hundreds of columns - manually specifying types is quite tedious.

**Comment by thermokarst** [comment]
I'm not sure about the q2-sample-classifier issue, I'll wait to hear what @nbokulich says.

RE the `q2:types` directive, here is another passage from the doc linked to above (emphasis mine):

> The row’s first cell must be #q2:types to indicate the row is a comment directive. Subsequent cells may contain the values categorical or numeric (both case-insensitive). **The empty cell is also supported if you do not wish to assign a type to a column (the type will be inferred in that case). Thus, it is easy to include this comment directive without having to declare types for every column in your metadata.**

**Comment by nbokulich** [comment]
Hey @mortonjt thanks for pulling me in. RE: q2-sample-classifier tbh I think I had this same discussion with @thermokarst a few years ago when developing that plugin (using the types directive was the solution at the time). Indeed this is a common issue, since many times class labels are numerically encoded.

We could consider moving this discussion over to q2-sample-classifier, but it sounds like this is not isolated to that plugin so a solution there would not help us unless if that is your primary target for this.

My two cents on #588 : relaxing MetadataColumn[Categorical] to accept int seems reasonable, but maybe it would be worth building in additional validation to check that int data look categorical, e.g., are not all unique values (or mostly unique values). Would that just make metadata validation too inefficient?

**Comment by antgonza** [comment]
>  e.g., are not all unique values (or mostly unique values). Would that just make metadata validation too inefficient?

@nbokulich, good idea ... my two cents, I guess the speed will depend on how it is done. A "quick" way is that the number of groups should be at most X% of the samples (taken from here: https://github.com/qiita-spots/qiita/issues/1595); for example, if we select 10% basically a categorical variable with 5 values should at least have 50 samples in the full dataset (independent of the distribution of those), 4 values 40 samples ...

**Comment by mortonjt** [comment]
I think making sure that 10% of metadata values aren't unique is a reasonable check - I can incorporate that in the PR. RE number of groups, that may require additional discussion since it isn't clear what threshold would be appropriate, since that could depend on the method right?  For instance, K-nearest neighbors won't care if about the number of class instances.

**Comment by thermokarst** [comment]
I'm not a big fan of the 10% approach - I think the current contract of "all or nothing" makes for a very predictable API. I think _if_ we wanted to pursue the 10% approach, we should mirror the current validation level approach in the `Format` API, that way we don't have a situation where some column types are treated differently from others (that sounds like a recipe for pain, to me). For those not aware, the `Format` API allows for formats to define two levels of validation, and different portions of the framework etc can take advantage of that when they need to (import performs full validation, while saving Results is minimum, if I recall correctly). For record-based formats (like Metadata) this usually looks like:

- min: validate the first 10-100 rows/records
- max: validate all of the rows/records

Alternatively, should we consider expanding the typing directive vocabulary here? The typing directive supports "numeric" and "categorical" data - is this an indication that a new type is needed? It just seems to me like these complaints are all solved relatively easily with the existing API, but I could certainly be missing something. Thanks for humoring me!

**Comment by nbokulich** [comment]
yeah I also don't like the 10% approach — it makes too many assumptions about the distribution. Even with a subsample I still worry that this will make metadata validation too inefficient.

It also sounds like the use case here is centered on q2-sample-classifier and related plugins, but we need to keep in mind that we must serve general use cases since Metadata touches everything... e.g., this comment:

>  For instance, K-nearest neighbors won't care if about the number of class instances.

makes me think we could/should address at the plugin level (since loosening type validation could have unintended consequences for other plugins, e.g., q2-diversity), or just the user level (which is what I do when running similar loops over a large number of int columns with q2-sample-classifier).

**Comment by mortonjt** [comment]
From what I'm seeing from this discussion there are two possible routes

Option 1 : Loosen the metadata types, but with careful validation.
Option 2 : Have everything go through the q2 directives as @thermokarst suggests.

The main reason why I haven't gone through Option 2 myself is because I'm still unfamiliar with the interface.  
Most of my metadata curation is done through jupyter notebooks, and I haven't spent the time to figure out how to programmatically format the q2 directives with writing the metadata files to disk.  I bet this is trivial, but I haven't seen any documented APIs on how to do this.  If there is `write_metadata(dataframe : pd.DataFrame, types : dict)` function in say q2-metadata, I think this would resolve my current issue.  Thoughts @thermokarst ?

**Comment by thermokarst** [comment]
I really like the idea of expanding some of the built-in tools - give me a few days to put my thoughts together on that, thanks @mortonjt!

**Comment by thermokarst** [comment]
Hey there @mortonjt, I put together a brief example which might help demonstrate how you can accomplish your proposed `write_metadata`, today, by casting your dataframe values _prior_ to constructing your QIIME 2 Metadata:

```python
import os
import qiime2
import pandas as pd
import tempfile

def roundtrip_md(md):
    with tempfile.TemporaryDirectory() as fh:
        fp = os.path.join(fh, 'md.tsv')
        md.save(fp)

        with open(fp) as written:
            print('\ncontents of md file:')
            print(written.read())


df = pd.DataFrame({'foo': [1, 2, 3], 'bar': [4, 5, 6]},
                  index=pd.Index(['a', 'b', 'c'], name='id'))
print(df)
print(df.dtypes)

md1 = qiime2.Metadata(df)
print(md1)
roundtrip_md(md1)

md2 = qiime2.Metadata(df.astype({'foo': 'str'}))
print(md2)
roundtrip_md(md2)
```

output
```
    foo  bar
id          
a     1    4
b     2    5
c     3    6
foo    int64
bar    int64
dtype: object
Metadata
--------
3 IDs x 2 columns
foo: ColumnProperties(type='numeric')
bar: ColumnProperties(type='numeric')

Call to_dataframe() for a tabular representation.

contents of md file:
id	foo	bar
#q2:types	numeric	numeric
a	1	4
b	2	5
c	3	6

Metadata
--------
3 IDs x 2 columns
foo: ColumnProperties(type='categorical')
bar: ColumnProperties(type='numeric')

Call to_dataframe() for a tabular representation.

contents of md file:
id	foo	bar
#q2:types	categorical	numeric
a	1	4
b	2	5
c	3	6
```

In this case, any files that are written using `Metadata.save()` will already have the correct q2:types directive, already.

**Comment by mortonjt** [comment]
Awesome, thanks @thermokarst ! Since it looks like the existing API already accommodates this proposed change, I'm going to close this issue.

**Comment by antgonza** [comment]
@thermokarst, thank you for the code.

If I understand correctly, the idea of your code is that it should be added in each individual plugin, correct? If yes, what do you think about adding to all q2 a flag like what has been suggested before so they can be exposed automatically: https://github.com/qiime2/qiime2/issues/568#issuecomment-803000730? If not possible, is there a "quick" way to find all the plugins that require a specific column as input so we can add that flag?

If you are wondering why I still think this is important in adding to all available plugins (and I'll be willing issuing PRs for this) is that  IMOO there is one important point missing based on my own analyses and other Qiita/QIIME 2 users: it would be ideal if it could be possible to control how to use a given metadata column (categorical or numeric) without having to actively change the `#q2:types` row AKA change the behavior via parameters in the command. For example, a numeric column representing time, could be used as numeric in a PCoA plot but also as different groups in distance matrix group significance.

**Comment by ebolyen** [comment]
Jumping in late here, but I think @thermokarst's solution is geared more towards something a user (or interface) would perform, instead of the plugin. More or less, it seems that metadata's typing feature handles this situation well enough, there's just maybe not enough documentation in the user tutorials on using it in practice. 

If there were some kind of on the fly type-casting for columns, I think it would make sense as an extended syntax in a CLI, rather than something added as a parameter (no need to search and modify plugins here). The interface is after all, ultimately responsible for providing the metadata to the plugin, and there's no reason it couldn't do type coercion on request. (If you think about it, that's exactly what Matt's example above is doing.)

Re: your point, I think time is a good example of something where we would want something like a `Date` or `Time` type. Someone would have to come up with rules for when a string is a member of that type, but we could consider such a type to be both numeric and categorical pretty easily, although I expect binning time would be the more typical way to convert it to categorical (technically ordinal/still time).

Similarly, more granular types are possible (i.e. "levels of measurement"), but there isn't much consensus on their utility, and as most larger systems (like R and Galaxy) get by with just the two (recently time is common), so we haven't exactly jumped to realize those more complex hierarchies.

**Comment by mortonjt** [comment]
+1 for Date/Time type, since it comes with concrete units.

**Comment by antgonza** [comment]
Thank you @ebolyen. I think adding specific types, would help but not completely fix the issue: users will still need to cast for specific scenarios or data by changing the `#q2:types` row. Additionally, we could end up with more data types that we really want to deal with. Another example that comes to mind: serialized "numeric" host subject ids - this could represent the categorical host unique id but also, as they are serialized, a proxy to when the sample was created in the system which could be used as a numeric value and potentially useful for other analyzes.

>  I think it would make sense as an extended syntax in a CLI
I think I agree with this, one option is that whenever `MetadataColumn[Numeric |Categorical]` is used, there is an automatic flag added, like `--force-case` (or whatever you think best), so the casting is forced; then this will be available for users and stored in the provenance. The user has the flexibility to do it and it is keep in the records. What do you think?

**Comment by antgonza** [comment]
@ebolyen, just wondering if you have any thoughts about the proposed flag; if you + other devs agree, I can work on a PR to add it.

**Comment by ebolyen** [comment]
Hey @antgonza,

We're actually about to start a project to make this a little simpler on the command line. It isn't exactly a flag that is added everywhere, but it will make this simpler for users hopefully.

**Comment by antgonza** [comment]
Thank you so much! Please let me know if you need help with code, reviews or testing ... looking forward to this addition.
