### ISSUE TITLE
Install QIIME 2 Artifact API without full QIIME2 installation.

### ISSUE THREAD

**Issue by LeeBergstrand** [qiime2/qiime2#570]
I'm currently prototyping a python-based microbiome analysis library—just something simple to automate the generation of custom taxa plots and perhaps some scikit-learn based PCA analysis. I wondered if there was a way to access the Artifact API without doing a complete QIIME2 installation? Specifically, I'm interested in being able to open feature-table and taxonomy `.qza` files.

My core questions are the following:

- How would I install just the core QIIME2 framework to support the Artifact API without unnecessary plugins and underlying programs?
- Is this download possible through Conda?
- Would I have to create a second Conda installer that only installs the python package contained in https://github.com/qiime2/qiime2? 
- Would there be a workaround for parsing the table out of a `.qza` file without the Artifact API?

**Comment by thermokarst** [comment]
> I'm currently prototyping a python-based microbiome analysis library—just something simple to automate the generation of custom taxa plots and perhaps some scikit-learn based PCA analysis.

This sounds awesome! Please share with us when you're ready, we would love to see.

> I wondered if there was a way to access the Artifact API without doing a complete QIIME2 installation?

Definitely! I'll post some details below. We are also actively working on rebuilding https://library.qiime2.org to assist with building these kinds of custom deployments, more on that later this year!

> How would I install just the core QIIME2 framework to support the Artifact API without unnecessary plugins and underlying programs?

```bash
conda create \
  -n my-custom-qiime2-env \
  -c qiime2 \
  -c conda-forge \
  -c bioconda \
  -c defaults \
  --override-channels \
  qiime2
```

If you want common data types, include `q2-types` in that list above.

> Is this download possible through Conda?

Yes! Please see above. https://anaconda.org/qiime2

> Would I have to create a second Conda installer that only installs the python package contained in https://github.com/qiime2/qiime2?

Please see my response above with the `conda create ...` command.

> Would there be a workaround for parsing the table out of a .qza file without the Artifact API?

[QZA files are just ZIP files](https://dev.qiime2.org/latest/storing-data/): `mv my-table.qza my-table.zip && unzip my-table.zip`.

If you have additional questions it might be helpful to move the discussion over to our [Developer Discussion channel on the QIIME 2 Forum](https://forum.qiime2.org/c/dev-discussion/7), that way more of our community can get involved.

**Comment by LeeBergstrand** [comment]
@thermokarst Thanks for the information. When I get the library more fleshed out I'll let you know.
