### ISSUE TITLE
Qiime taxa collapse-problem?

### ISSUE THREAD

**Issue by Sammijiyoung** [qiime2/qiime2#581]
Hi all!

I have a problem with qiime taxa collapse script..
I honestly cannot find the reason why.. 

I am running this on Mac Qiime 2,

Here is the script that I am running:

qiime taxa collapse
--i-table dada2_trial/table.qza
--i-taxonomy 99_otu_classifier_trial.qza
--p-level 7
–-o-collapsed-table table_trial.qza 

I made sure my taxonomy file is the one from Greengene Database classifier
and the Error Msg seems to be related to –-o-collapsed-table ???

Here is the error msg:

(1/2) Missing option '--o-collapsed-table'. ("--output-dir" may also be
used)
(2/2) Got unexpected extra argument ( )
/var/lib/slurmd/job2224692/slurm_script: line 22: –-o-collapsed-table: command not found

My script includes the Missing option...so I don't understand why it doesn't recognize it????
Can anyone tell??? what's wrong??

I am using this script to create OTU table..which we need for running analysis on Galaxy/Metagenassist..on different platform.

**Comment by thermokarst** [comment]
Hi @Sammijiyoung! We provide user support over at https://forum.qiime2.org - please post your question over there and someone will be with you soon.
