### ISSUE TITLE
Idea : Canned metadata formats / transformers

### ISSUE THREAD

**Issue by mortonjt** [qiime2/qiime2#583]
**Improvement Description**
Create some form of cookie cutter default formatter for new metadata types.

**Current Behavior**
Almost every qiime2 plugin wants to output some metadata format in some form, whether it be taxonomies, genes annotations or even just summary stats.

**Proposed Behavior**
But given how ubiquitous metadata types are, it maybe worthwhile to design a cookie-cutter tools / templates to quickly flesh out transformers, formats for new metadata types.  Designing new metadata types is currently the bottleneck for my upcoming plugins and I imagine that this is the main hurdle for new q2 developers.  It could be as simple as creating a new `plugin.register_metadata_type` or something like that that auto-generates all of the relevant formats / transformers.

**Comment by nbokulich** [comment]
I agree, making some kind of base class for generic dataframe-like formats would make sense and reduce some boilerplate for defining new semantic types.

Just to comment quickly on some of your comments:
> whether it be taxonomies

FeatureData[Taxonomy] should be used for such outputs

> genes annotations

for generic annotations (e.g., mapping sequence IDs to an annotation) this could already probably output as FeatureData[Taxonomy]. We are working on defining new types/formats for gene and genome annotations specifically, so more on that soon.

**Comment by mortonjt** [comment]
I gave the Taxonomy type as an example, since it is already a slick metadata type.  
But there are many others, such as the DADA2Stats or the SongbirdStats types.  I just pushed in a new type I called [Matching](https://github.com/mortonjt/q2-differential/pull/17), just so that I could append a new column to my metadata table. 

Given how prolific these sort of types are there is much potential to save a substantial amound of developer time in the future with a unified data-frame type.

**Comment by antgonza** [comment]
I really like this. 

This topic just came up within a discussion with @mortonjt that one of the possible problem of creating more types is that developers will forget to create/add transformers (like this: https://github.com/flatironinstitute/q2-matchmaker/issues/31) and it seems like a lot of duplication of code. In specific, the matching example above is really similar to the alpha diversity results.

**Comment by gregcaporaso** [comment]
I think the `ImmutableMetadata` semantic type covers this now. Basically, as long as a file could be loaded into a `qiime2.Metadata` object, it can be output with semantic type `ImmutableMetadata`. This could then be used anywhere a metadata file could be used (e.g., `qiime metadata tabulate`) or exported to .tsv. 

Closing this, but let me know if this doesn't capture what you're going for.
