### ISSUE TITLE
qiime2 in jupyter notebook

### ISSUE THREAD

**Issue by khemlalnirmalkar** [qiime2/qiime2#589]
Hi,
How to use qiime2 in jupyter notebook?
how can I import qiime2?
Thanks,
.

**Comment by khemlalnirmalkar** [comment]
> Hi,
> How to use qiime2 in jupyter notebook?
> how can I import qiime2?
> Thanks,
> .

Got, thanks

**Comment by thermokarst** [comment]
Hi @khemlalnirmalkar - we provide user support over at https://forum.qiime2.org - please post this question there if you still require assistance. This helps us provide timely support to all who need it - thanks for your cooperation.
