### ISSUE TITLE
Improve error message when v0 artifact passed as metadata

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/qiime2#592]
**note**
There are few v0 Artifacts in the wild, so this is an unlikely scenario. I'm filing this issue mostly to create a searchable record of the behavior in case someone manages to trigger it. Feel free to close this.

**Improvement Description**
The error message produced when a v0 artifact is passed as metadata to a QIIME 2 command refers to internal details of the Artifact, and might be confusing to users.  
![image](https://user-images.githubusercontent.com/39198770/125002464-d8b4ff00-e009-11eb-8248-9d17b3d8307d.png)

Searchably:
`[Errno 2] No such file or directory: '/tmp/qiime2-archive-_ujdpbgc/fe01b51d-0944-4572-9dfc-77d87cc01b42/provenance'`

**Current Behavior**
QIIME 2 attempts to read from `provenance`, which does not exist. The error above is raised when `provenance.py`'s `add_ancestor` calls `shutil.copy_tree()` on the nonexistent path, and the command fails to run.

**Proposed Behavior**
Handle this gracefully... somehow? Or more likely, if you are a QIIME 2 users, try to avoid v0 Artifacts or recreate them using a non-alpha version of QIIME 2?

**Comment by thermokarst** [comment]
> Or more likely, if you are a QIIME 2 users, try to avoid v0 Artifacts or recreate them using a non-alpha version of QIIME 2?

I don't think this is a case that needs to be solved - we don't need to worry about supporting alpha APIs in current versions of QIIME 2, and similarly, I don't think I have seen any QIIME 2 v0 Artifacts out in the wild in a very long time (2017? 2018?).

**Comment by ChrisKeefe** [comment]
Totally understood. Closing this now - just wanted it to be available for posterity.
