### ISSUE TITLE
AttributeError: <class 'qiime2.core.type.grammar.UnionExp'> object has no attribute 'decode'

### ISSUE THREAD

**Issue by johnchase** [qiime2/qiime2#593]
**Bug Description**
I am using `decode_parameters` to decode the inputs to a plugin action. For some plugins this works as expected, however, for others it fails.

**Steps to reproduce the behavior**
The following fails:

```python
import qiime2
PLUGIN_MANAGER = qiime2.sdk.PluginManager()

method = PLUGIN_MANAGER.plugins["feature-classifier"].actions["classify_sklearn"]

job_params = {
    "reads_per_batch": "auto",
    "n_jobs": "1",
    "pre_dispatch": "2*n_jobs",
    "confidence": "0.7",
    "read_orientation": "auto",
}

method.signature.decode_parameters(**job_params)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a4066188cdc2> in <module>
     21             job_params[parameter["parameter_name"]] = parameter["value"]
     22     print(job_params)
---> 23     _ = method.signature.decode_parameters(**job_params)
     24     print(job_params)

~/miniconda3/envs/kamino/lib/python3.8/site-packages/qiime2/core/type/signature.py in decode_parameters(self, **kwargs)
    318                 params[key] = None
    319             else:
--> 320                 params[key] = spec.qiime_type.decode(kwargs[key])
    321         return params
    322 

~/miniconda3/envs/kamino/lib/python3.8/site-packages/qiime2/core/type/grammar.py in __getattr__(self, name)
     55             return getattr(self.template, name)
     56 
---> 57         raise AttributeError("%r object has no attribute %r"
     58                              % (type(self), name))
     59 

AttributeError: <class 'qiime2.core.type.grammar.UnionExp'> object has no attribute 'decode'
```
Other actions work without issue, for example:

```python
job_params = {
    "trunc_len_f": 0,
    "trunc_len_r": 0,
    "trim_left_f": 19,
    "trim_left_r": 20,
    "max_ee_f": 2.0,
    "max_ee_r": 2.0,
    "trunc_q": 2,
    "pooling_method": "independent",
    "chimera_method": "consensus",
    "min_fold_parent_over_abundance": 1.0,
    "n_threads": 1,
    "n_reads_learn": 1000000,
    "hashed_feature_ids": "true",
}

method = PLUGIN_MANAGER.plugins["dada2"].actions["denoise_paired"]
method.signature.decode_parameters(**job_params)
```

**Expected behavior**
I expect `method.signature.decode_parameters` to return a dictionary of parameters that can be passed into the method call

**Computation Environment**
- Ubuntu 20.04.2 LTS
- QIIME 2 Release 2021.4.0

**Comments**
I'm not sure I understand what is happening behind the scenes enough to understand why parameters are being assigned to different types behind the scenes. Perhaps this is expected, but I am misudnerstanding the use of `decode_parameters`?

I saw this same error referenced in the [forum](https://forum.qiime2.org/t/error-after-denoising-protocols/14461) but don't know if it was ever resolved

**Comment by ebolyen** [comment]
Whoops, no that's on us, `decode_parameters` should probably be updated, but most of our interfaces use `parse_primitive` from `qiime2.sdk.util` instead, which should handle this correctly.

It used to be the case that a single expression only ever had a single type, and so a `decode` made sense. This isn't true anymore with things like `Int % Range(...) | Str % Choices(...)`, and [`parse_primitive`](https://github.com/qiime2/qiime2/blob/1f8c27da94c524cc0f4a5fd2e6f3155229c0d9fd/qiime2/core/type/util.py#L183) was added to handle this in a more complete way.

Also as a heads up, this helper can be given ASTs instead of expression strings, which are useful if a type variable exists in your expression (as the only way we have to produce the complete context of those is via the AST)

**Comment by johnchase** [comment]
@ebolyen Thanks for the quick response! I was not aware of `parse_primitive` as far as I can tell it is working how I would expect
