### ISSUE TITLE
Inconsistent `import_from_format` parameter naming between Usage and its implementations

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/qiime2#612]
**Bug Description**
[`usage.Usage.import_from_format`](https://github.com/qiime2/qiime2/blob/39ac17da01e22057ff38197eb23ad6cca48f4c2e/qiime2/sdk/usage.py#L925) takes a parameter named `variable` in the third position.

[`ArtifactAPIUsage.import_from_format`](https://github.com/qiime2/qiime2/blob/6ef6df712f2f14be1baa5551368a41c3e9f8e340/qiime2/plugins.py#L190) and [`CLIUsage.import_from_format`](https://github.com/qiime2/q2cli/blob/bee9b88bc5a9a8beb116f5252d68a4b85361cbec/q2cli/core/usage.py#L136) both use `fmt_variable` in the same position.

Users who approach usage examples from the [docs](https://dev.qiime2.org/latest/api-reference/usage/authors/#importing) are likely to pass keyword arguments to this method, given that the rendered example does so. (I certainly did). 

**Proposed solutions**
Rename the variable variable-name to `variable` in all child Usages, so it aligns with the parent. This keeps the published API stable, even if the name is a little unspecific. We could also make these arguments positional-only, which is restrictive and a little gross but more explicitly indicates that implementations may not share variable names, and means that users get a more explicit error message: 

![image](https://user-images.githubusercontent.com/39198770/148309389-eb8c042b-fabf-4278-ab30-6a69b7e960aa.png)

**Screenshots**
This error message left me wondering if I'd misspelled something:
![image](https://user-images.githubusercontent.com/39198770/148309149-7e19e6c4-ec57-46c7-b78d-a048a1b608c9.png)

Happy to ship a PR for this if that's useful.

**Comment by ebolyen** [comment]
I ran into this also at one point, I agree that the name should be `variable` in the child classes. I suspect since they both have this same incorrect name, it just reflects an older revision of the idea.

**Comment by thermokarst** [comment]
Yep, it was just some leftovers from an earlier draft that never got cleaned up.

**Comment by thermokarst** [comment]
BTW, PRs to clean this up would be greatly appreciated, thanks!
