### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links ; in installing qiime2

### ISSUE THREAD

**Issue by Shinya432** [qiime2/qiime2#615]
Hello
I had this problem when I tried to install qiime2 after installing miniconda3 because I wanted to analyze bioinformatics with ubuntu on WSL.
I'm just starting to study Linux and I don't understand why this happened.

conda env create -n qiime2-2021.11 --file qiime2-2021.11-py38-linux-conda.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda_env/installers/conda.py", line 59, in install
        unlink_link_transaction.execute()
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 245, in execute
        self.verify()
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 232, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 591, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 412, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/c/ubuntu/miniconda3/lib/python3.8/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/c/ubuntu/miniconda3/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/c/ubuntu/miniconda3/bin/conda-env create -n qiime2-2021.11 --file qiime2-2021.11-py38-linux-conda.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
   CONDA_BACKUP_JAVA_HOME=
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/c/ubuntu/miniconda3/bin/conda
             CONDA_PREFIX=/mnt/c/ubuntu/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/c/ubuntu/miniconda3/bin/python
               CONDA_ROOT=/mnt/c/ubuntu/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/mnt/c/ubuntu/miniconda3/jre/lib/amd64/server
                     PATH=/mnt/c/ubuntu/miniconda3/bin:/mnt/c/ubuntu/miniconda3/bin:/mnt/c/ubunt
                          u/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsA
                          pps/CanonicalGroupLimited.UbuntuonWindows_2004.2021.825.0_x64__79rhkp1
                          fndgsc:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/
                          Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/Sys
                          tem32/OpenSSH:/mnt/c/Users/shiny/AppData/Local/Programs/Python/Python3
                          8-32/Scripts:/mnt/c/Users/shiny/AppData/Local/Programs/Python/Python38
                          -32:/mnt/c/Users/shiny/AppData/Local/Microsoft/WindowsApps:/mnt/c/User
                          s/shiny/AppData/Local/atom/bin:/mnt/c/Users/shiny/AppData/Local/Micros
                          oft/WindowsApps:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mnt/c/ubuntu/miniconda3
            shell level : 1
       user config file : /mnt/c/ubuntu/.condarc
 populated config files : /mnt/c/ubuntu/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/c/ubuntu/miniconda3  (writable)
      conda av data dir : /mnt/c/ubuntu/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /mnt/c/ubuntu/miniconda3/pkgs
                          /mnt/c/ubuntu/.conda/pkgs
       envs directories : /mnt/c/ubuntu/miniconda3/envs
                          /mnt/c/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.10 Linux/4.4.0-19041-Microsoft ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by thermokarst** [comment]
Hi @Shinya432, please ask this at forum.qiime2.org, that is where we provide support at. Thanks!

**Comment by Shinya432** [comment]
Thank you @thermokarst 
I'm sorry that I misunderstood the place to ask a question. Thank you for letting me know the site.
