### ISSUE TITLE
Support INSDC NULL values in metadata

### ISSUE THREAD

**Issue by antgonza** [qiime2/qiime2#616]
**Addition Description**
Support INSDC NULL values in metadata 

**Current Behavior**
When a numeric type has INSDC NULL value the conversion fails with:
```
Cannot convert metadata column 'bmi' to numeric. The following values could not be interpreted as numeric: 'not applicable'
```

**Proposed Behavior**
Allow [all INSDC lower level terms](https://ena-docs.readthedocs.io/en/latest/submit/samples/missing-values.html) to be nulls while processing metadata.

**Questions**
1. Should any casing be supported or only all lower?

**Comments**

**References**
https://ena-docs.readthedocs.io/en/latest/submit/samples/missing-values.html

**Comment by jworkman01** [comment]
I am l looking to contribute to this open source project for my software development methodology class. Is this issue still available?

**Comment by thermokarst** [comment]
Hi @jworkman01 - this issue has not been decided on yet, I'm not even sure if this is something we will support or not. If you're interested in finding open issues in the QIIME 2 ecosystem, please check this link: https://github.com/search?q=org%3Aqiime2+state%3Aopen&type=Issues

Thanks!

**Comment by jworkman01** [comment]
Okay I'll take a look, thanks!

**Comment by ebolyen** [comment]
Hey @antgonza, just a heads up that I'm looking into how we would implement this for the April release.
I'm going to do a quick review of existing "ontological work" in this space to make sure we can support INSDC as well as any other things I come across. If you have any recommended readings, let me know!

**Comment by antgonza** [comment]
Thank you @ebolyen! I think for supporting the lower level terms and if possible the top level values would be great: https://www.insdc.org/missing-value-reporting. Note that we try to keep everything in Qiita lowercase but perhaps making it case insensitive would be a good idea; not sure.
