### ISSUE TITLE
Plugin error from dada2

### ISSUE THREAD

**Issue by Ye-Yonglian** [qiime2/qiime2#628]
When I am using dada2, the following problem occurs：

- Plugin error from dada2:
- An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.
- Debug info has been saved to /home/sun/tempo/qiime2-q2cli-err-clot_a5i.log

and the .log tell me : there is no package called ‘GenomeInfoDbData’ but I don't know which folder it should be placed in. 

Can you help me ? please...

**Comment by nbokulich** [comment]
Hi @Ye-Yonglian , all user support questions should be directed to the QIIME 2 forum. Thanks!
