### ISSUE TITLE
Need to replicate the same DADA2 options in R into qiime2 with PacBio CCS reads

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/qiime2#629]
Hi,

I processed PacBio ccs reads in R but I am interested in using Qiime2 after adding new plugins for 16S ccs reads. I followed the tutorial posted here; https://github-wiki-see.page/m/PacificBiosciences/pb-16S-nf/wiki/Analyzing-PacBio-HiFi-Mock-Community-16S-Data-with-QIIME-2
The issue is that I need to use the pooling option and SILVA 138.1 version as in DADA2 tutorials.
The community's help and suggestions are much appreciated!
Thanks!

**Comment by nbokulich** [comment]
Hi @emankhalaf , all user support questions should be directed to the QIIME 2 forum. In this case, though, your question seems to be about a github repository from another organization, so I suggest that you pose your question directly to the writers of that tutorial. Thanks!
