### ISSUE TITLE
Error message in samples.demux.summary.qzv of PacBio 16S ccs reads

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/qiime2#630]
Hi,

I got this error message when importing PacBio 16S ccs reads
Danger: Some of the forward PHRED quality values are out of range. This is likely because an incorrect PHRED offset was chosen on import of your raw data. You can learn how to choose your PHRED offset during import in the importing tutorial.

The code that I use is 
qiime tools import --type 'SampleData[SequencesWithQuality]' \
 --input-path manifest.txt \
 --output-path samples.qza \
 --input-format SingleEndFastqManifestPhred33V2

Any help, please!

Thanks!

**Comment by nbokulich** [comment]
Hi @emankhalaf , all user support questions should be directed to the QIIME 2 forum. Thanks!
