### ISSUE TITLE
Could not install Qiime configuration as i get this message on Anaconda: Unable to locally verify the issuer's authority. To connect to data.qiime2.org insecurely, use `--no-check-certificate

### ISSUE THREAD

**Issue by hadeerIsmail22** [qiime2/qiime2#631]
Have you had a chance to check out the docs?
https://docs.qiime2.org
There are many tutorials, walkthroughs, and guides available.

If you still need help, please visit:
https://forum.qiime2.org/c/user-support

Help requests filed here will not be answered.

**Comment by hadeerIsmail22** [comment]
please could you help me to install Qiime2 on my Windows10, i have a problem in installing the configuration step

**Comment by hadeerIsmail22** [comment]
Sorry, but what do you mean with that #631?


Sent from Hadeer Ismail  


On Monday, August 1, 2022, 7:32 PM, Evan Bolyen ***@***.***> wrote:




Closed #631 as completed.

**Comment by hadeerIsmail22** [comment]
I tried these bash


    On Monday, August 1, 2022 at 09:02:15 PM GMT+2, Yahoo Action ***@***.***> wrote:  
 
 Sorry, but what do you mean with that #631?


Sent from Hadeer Ismail  


On Monday, August 1, 2022, 7:32 PM, Evan Bolyen ***@***.***> wrote:




Closed #631 as completed.

**Comment by ebolyen** [comment]
Hi Hadeer,

Sorry I assumed you would have seen my reply to your previous email first. We answer questions on the [QIIME 2 Forum](https://forum.qiime2.org).

**Comment by hadeerIsmail22** [comment]
Thank you 


Sent from Hadeer Ismail  


On Monday, August 1, 2022, 9:46 PM, Evan Bolyen ***@***.***> wrote:




Hi Hadeer,

Sorry I assumed you would have seen my reply to your previous email first. We answer questions on the QIIME 2 Forum.
