### ISSUE TITLE
enable metadata merging when no sample ids overlap

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#633]
At present, sample metadata merging functions by intersecting the sample ids in the metadata files and as a result doesn't support metadata files with no overlapping sample ids. It would be useful to enable merge when no sample ids overlap. This would be particularly useful for pooled analyses, where samples from two or more different studies are integrated in a single analysis (e.g., contextualizing new data with pre-existing HMP or EMP samples). At present, this requires a manual merge of metadata files, which is error-prone and can lead to a proliferation of different metadata files (which is bad for a lot of reasons). 

**Challenges**
1. In many cases, sample ids across studies will be entirely different. However there may be some commonly used sample names, for example `control.1`, `blank.2`, ... In this case, based on current behavior, the resulting metadata would be only the metadata associated with those samples (i.e., it would default to the sample id intersection behavior). This would result in users sometimes getting unexpected results that could require them to modify their input metadata (e.g., comment out records) or would require new functionality to tell QIIME 2 how to handle overlapping sample ids.

**Comment by lizgehret** [comment]
Hey @gregcaporaso - I'm pretty sure we can close this one as completed, correct? All of the functionality you mentioned is essentially included in this PR (just with a slightly different approach than what you mention above):

https://github.com/qiime2/q2-metadata/pull/60

**Comment by gregcaporaso** [comment]
Yep, thanks!

**Comment by gregcaporaso** [comment]
Yep, thanks!
