### ISSUE TITLE
Errors building QIIME2 environment using latest mamba version and strict channel priority

### ISSUE THREAD

**Issue by AKBrueggemann** [qiime2/qiime2#638]
While updating my code I ran into the problem that the environment for QIIME2 can no longer be built from the corresponding yaml file when using the newest mamba version and strict mode as channel priority. Sadly I can't change the settings concerning the mamba version and the channel priority, because they are set in the GitHub action I use. 
So far, all perl-based packages lead to the error "Can not be installed because of strict repo priority".
Deleting the version numbers in the yaml file for the said packages helps, but it would be nice if the environment could be built without these changes.

**Comment by Oddant1** [comment]
Hey, sorry this fell by the wayside. We have a lot of issues across the entire org and are currently looking at cleaning them up. If this is still an issue you're having please post it under the Technical Support category on the [QIIME 2 forum](https://forum.qiime2.org/)
