### ISSUE TITLE
Creating metadata for dada2 output in qiime2

### ISSUE THREAD

**Issue by Vetshweta** [qiime2/qiime2#651]
Hi, I am working on microbiota analysis for sequence obtained from shoreline biome kit. I have obtained ASV .tax file, .biom feature table and ASV .fasta file from DADA2 pipeline following the analysis protocol provided by the shoreline biome. 
I am using linux terminal and have imported them as:

##importing data in qiime Import the ASV .tax feature taxonomy into Qiime2

qiime tools import --input-path taxonomy.tax  --type 'FeatureData[Taxonomy]' --input-format HeaderlessTSVTaxonomyFormat --output-path taxonomy.qza

##Import the .biom feature table into Qiime2

qiime tools import --input-path DADA_sequence_table_nochiR.biom --type 'FeatureTable[Frequency]' --input-format BIOMV100Format --output-path table.qza

##Import the ASV .fasta file into Qiime2

qiime tools import --input-path DADA_ASVs_only_nochiR_md5.fasta --type 'FeatureData[Sequence]' --output-path rep_seqs.qza

##creating metadata
qiime metadata tabulate --m-input-file rep_seqs.qza --m-input-file taxonomy.qza --o-visualization tabulated-feature-metadata.qzv

###exporting metadata 
qiime tools export --input-path tabulated-feature-metadata.qzv --output-path metadata.tsv

###FeatureTable and FeatureData summaries
qiime feature-table summarize --i-table table.qza --o-visualization table.qzv --m-sample-metadata-file metadata.tsv

**The problem is with feature table summarize. It gives an error saying :**

Plugin error from feature-table:

 The following IDs are not present in the metadata: '103AOC', '103I2A', '103I2B', '103aBC', '103aI1A', '103aI1B', '103aI3A', '103aI3B', '103aIF10', '103aNI1A', '103aNI1B', '103aNI2A', '103aNI2B', '103aNI3A', '103aNI3B', '103aNIF10', '103aNIF28', '103aSC', '62aBC', '62aFS', '62aI1A', '62aI1B', '62aI2A', '62aI2B', '62aI3A', '62aI3B', '62aIF10', '62aIF28', '62aNI1A', '62aNI1B', '62aNI2A', '62aNI2B', '62aNI3A', '62aNI3B', '62aNIF10', '62aNIF28', '62aOC', 'BGF2', 'BGF_CC_0_01_1', 'BPA1', 'BPA_0_01_1', 'BPA_0_01_2', 'BPA_0_1_2', 'BPF1', 'BPF2', 'BSA_0_01_1', 'BSA_0_01_2', 'BSA_0_1_1', 'BSA_0_1_2', 'CI1A', 'CI1B', 'CI2A', 'CI2B', 'CI3A', 'CI3B', 'CIF10', 'CIF28', 'CNI1A', 'CNI1B', 'CNI2A', 'CNI2B', 'CNI3B', 'CNIF10', 'CNIF28', 'Cp641', 'E22', 'MI1A', 'MI1B', 'MI2A', 'MI2B', 'MI3A', 'MI3B', 'MIF10', 'MIF28', 'MNI1A', 'MNI1B', 'MNI2B', 'MNI3A', 'MNI3B', 'MNI3F10', 'MNI3F28', 'NT1', 'NT2', 'VC1', 'VC2'

Debug info has been saved to /tmp/qiime2-q2cli-err-m0rr4pe2.log

Also, how do I add column in metadata with treatment group name, and challenges information?

**Comment by lizgehret** [comment]
Hi @Vetshweta - please post this question on our user forum, found [here](https://forum.qiime2.org/). This is where you can ask for help regarding the usage of QIIME 2 and any technical issues you may be running into regarding your analysis. Github issues should only be filed if there is an actual bug in our code, or new feature/improvement you'd like to see developed. Thanks!
