### ISSUE TITLE
Should `.async` type-check before spawning?

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#66]
**Comments**
This would make life a little easier for users of the "Artifact" API in a Jupyter notebook, etc... as they wouldn't need to call `future.result()` over and over to see if it "worked", but it wouldn't prevent all types of errors as the wrapped function may still raise. Additionally this will make it harder for interface developers who would need to catch errors and represent them from two different places.

**Comment by Oddant1** [comment]
@ebolyen This is still not happening, but I'm not sure if we really care. Reopen if you think we care.
