### ISSUE TITLE
ResultCollections of ProxyArtifacts don't work when returned from a pipeline

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#687]
**Bug Description**
It is not possible to return a collection (list, dict, or otherwise) of ProxyArtifact's as this situation is missed by the final stages of the pipeline executor. The result is an error indicating that `ProxyArtifact` is not in instance of `Result`.

**Workaround**
```python
def some_pipeline(ctx, ...):
    # stuff
    ...
    # before returning the collection:
    for key, value in results.items():
        results[key] = value.result()
    return results
```

**Comment by Oddant1** [comment]
Do we want to support any degree of nesting here?

**Comment by ebolyen** [comment]
I don't think so, since collections don't nest themselves.
