### ISSUE TITLE
qiime not installed (env created from .yml file)

### ISSUE THREAD

**Issue by BCArg** [qiime2/qiime2#689]
The issue is described in detail here [here](https://github.com/aomlomics/tourmaline/issues/104)

I have tried an older yml file (https://raw.githubusercontent.com/qiime2/environment-files/master/2022.2/release/qiime2-2022.2-py38-linux-conda.yml) and from the environment created with this yml file I can invoke qiime.

Conda version is `23.1.0`

**Comment by Oddant1** [comment]
Hello @BCArg, please create a thread for this issue under the technical support category on the QIIME 2 user forum [here](https://forum.qiime2.org/). You will receive support from QIIME 2 maintainers there. Thank you.
