### ISSUE TITLE
Importing 'MultiplexedPairedEndBarcodeInSequenceDirFmt' requires a directory, not manifest.txt

### ISSUE THREAD

**Issue by Chiker7** [qiime2/qiime2#706]
Hello! I have a problem with qiime tools import...

#script:
qiime tools import \
--type MultiplexedPairedEndBarcodeInSequence \
--input-path manifest.txt \
--output-path import.qza
--input-format  MultiplexedPairedEndBarcodeInSequenceDirFmt

#problem
There was a problem importing manifest.txt:
  manifest.txt is not a directory.

I tried to remove the --input-format and encountered similar issues：
#problem
There was a problem importing manifest.txt:
  Importing 'MultiplexedPairedEndBarcodeInSequenceDirFmt' requires a directory, manifest.txt

And I tried to modify the file suffix to .tsv/.csv/...  useless...

by the way, my manifest.txt contains {sample-id, forward-absolute-path, reverse-absolute-path}.
I used this file to import as the type of 'SampleData[PairedEndSequencesWithQuality]', its sucessful. 

However, I want use the function of 'qiime cutadapt demux-paired', it requires '--i-seqs' : ARTIFACT PATH MultiplexedPairedEndBarcodeInSequence, The paired-end sequences to be demultiplexed.  [required]
So, I need to solve the import issue.

I would appreciate some assistance.
Many thanks,
Chiker

**Comment by Chiker7** [comment]
oh!
I tried creating a new file and imported two fastq.gz files named forward. fastq.gz and reverse. fastq.gz, and it was successful.
But I have a lot of data, how can I import it together?

**Comment by lizgehret** [comment]
Hi @Chiker7,

Please post this on the [QIIME 2 User Forum](forum.qiime2.org), as this is an error message you are receiving while attempting to use QIIME 2 (rather than an actual bug in the software, or feature request, etc). Thanks!
