### ISSUE TITLE
Enable OwnedPaths (i.e. FileFormat and DirectoryFormat with write mode) to initialize in a Cache

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#730]
**Addition Description**
This feature is largely for accelerating importing by avoiding unnecessary disk IO. 

**Current Behavior**
Currently creating an OwnedPath in QIIME 2 will use $TMPDIR which can be problematic if the destination is ultimately a Cache on a different block device. This will result in a copy of all of the data.

**Proposed Behavior**
We should have a mechanism to cause any instantiated OwnedPaths to appear in a target location. Plugin code/transformers should not be aware of this, so the immediate call-site will not control this. However the originating call-site (such as the Artifact/Python 3 API) should have a way to control it.

**Comment by ebolyen** [comment]
Related to importing IO: 

https://github.com/qiime2/qiime2/issues/721
https://github.com/qiime2/q2cli/issues/317

**Comment by Oddant1** [comment]
How exactly are we expecting this to work? Do we want these paths in the cache in some capacity? Is it time to roll out v2 of the cache with a tmp in it?

**Comment by ebolyen** [comment]
We could do it in the process pool (just like when we are setting up an artifact to link into data for the first time)

**Comment by Oddant1** [comment]
@ebolyen looking at this initially I interpreted it as "we should just instantiate OwnedPaths in the used cache as opposed to just all over in tmp" but looking at it again it seems like you want something to more generically allow the user to specify where these are instantiated? You use the term "target location" and say the originating call-site should be able to control this location.

**Comment by colinvwood** [comment]
I don't remember why this was assigned to me? @Oddant1

**Comment by lizgehret** [comment]
closed by #790
