### ISSUE TITLE
Create a `get_data_path` `plugin.util` helper to fetch from package resources

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#777]
Originally by @Oddant1 

We have the "get_data_path" function duplicated all over the place AND we have it as a method on TestPluginBase. We should probably consolidate this

**Comment by ebolyen** [comment]
There's also a number of other uses of `pkg_resources` which are deprecated and we should be using `importlib.metadata` instead.

**Comment by colinvwood** [comment]
Closing in favor of #792
