### ISSUE TITLE
Unable to download QIIME 2

### ISSUE THREAD

**Issue by katsudon2000** [qiime2/qiime2#778]
I am using a Linux (ubuntu 20.04) operating system from Azure. 
I have updated the conda version to the latest.

However, I am unable to download QIIME2 using this line of code `conda env create -n qiime2-amplicon-2024.5 --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml`

Does anyone have suggestions on how to solve this issue? Thank you in advance!

`$ conda env create -n qiime2-amplicon-2024.5 --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
Channels:
 - https://packages.qiime2.org/qiime2/2024.5/amplicon/released
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: | Killed`

**Comment by aimirza** [comment]
Set `conda config --set channel_priority flexible` before running the code. That worked for me.

**Comment by hagenjp** [comment]
@aimirza Thank you for your helpful input here!
@katsudon2000 I am going to close this issue. But if you are still stuck after trying @aimirza 's suggestion please reach out on the [qiime2 forum ](https://forum.qiime2.org) for help installing your environment. When you do please post your commands and the entire error message you receive when running  :) 
--Hannah
