### ISSUE TITLE
Kraken 2 issue:  'dict' object has no attribute 'type' 

### ISSUE THREAD

**Issue by JoelDTV** [qiime2/qiime2#781]
Hello Qiime2 community

I am working on a virtual machine with Rocky Linux. I have downloaded and uploaded the kraken2 pfp database successfully to Qiime, however when i tried to classify my sequences an AttributeError: 'dict' object has no attribute 'type' appeared.
Here is an outlook of the code that showed the aforementioned error

qiime moshpit classify-kraken2 --i-seqs /root/qiime2/SUELO_HOUSE/reads --i-kraken2-db /root/qiime2/moshpit_tutorial/cache/kraken2 --p-threads 100 --p-confidence 0.6 --p-minimum-base-quality 20 --o-hits /root/qiime2/moshpit_tutorial/cache/kraken_db_hits --o-reports /root/qiime2/moshpit_tutorial/cache/kraken_db_hits/kraken_db_reports --p-report-minimizer-data --use-cache /root/qiime2/moshpit_tutorial/cache --verbose --p-memory-mapping False

It took some 30 min or so, for the following message (screenshot enclosed) and the AttributeError: 'dict' object has no attribute 'type' to appear; after executing the above mentioned code.

![Screenshot from 2024-07-19 09-48-03](https://github.com/user-attachments/assets/bdfb2237-3d01-4925-b117-b963f5130082)

Can you shed some light on this? How can we solve the error?

Best

Joel T

**Comment by cherman2** [comment]
HI @JoelDTV, 
In order to keep things tidy, please keep user questions to the QIIME 2 Forum. We are going to close this issue out.
