### ISSUE TITLE
add `qiime2.util.get_filepath_from_package` API?

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#792]
[This](https://github.com/qiime2/q2-fmt/blob/b8161decabb490628abc4b39ba468496fc793ce4/q2_fmt/_examples.py#L15) is a pretty useful utility function for usage examples. Should we add a `Usage.get_filepath_from_tests` API?

**Comment by ebolyen** [comment]
My only concern is if this adds too much to the API. I think right now, all of the methods that a usage example uses implies strongly that the driver should do something as a consequence.

Whereas a utility like `Usage.get_filepath_from_tests` doesn't really have an equivalent utility to a driver. i.e. I don't _think_ we are asking to render a string or do anything from the interface side of things, we're just materializing some data for the factory right?

**Comment by gregcaporaso** [comment]
After discussing in the engineering meeting, we decided that this makes sense to add as `qiime2.util.get_filepath_from_package` (i.e., not a method on `Usage`).

We should update `TestPluginBase.get_data_path` to call this function internally.
