### ISSUE TITLE
zsh: no matches found: SampleData[PairedEndSequencesWithQuality]

### ISSUE THREAD

**Issue by aayushirambia** [qiime2/qiime2#796]
I am trying to run qiime2 through jupyterLab terminal in a mac for the first time, and I am getting this error. 
zsh: no matches found: SampleData[PairedEndSequencesWithQuality]
zsh: command not found: --input-path
zsh: command not found: --output-path
zsh: command not found: --input-format

I have checked the manifest file, the path to it and all of it seems to be correct. I am unable to figure out how to resolve this. I have been running qimme2 on a linux machine and never had any issues before. I am also a new mac user, so I am assuming I might be missing some basic thing. I would appreciate any help.

This is my sh file that I used to use in linux to run qiime2
#!/bin/bash/ 

qiime tools import 
--type SampleData[PairedEndSequencesWithQuality] 
--input-path /Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/qiime2_results/manifest 
--output-path input.qza 
--input-format PairedEndFastqManifestPhred33V2

qiime dada2 denoise-paired --i-demultiplexed-seqs input.qza --p-trim-left-f 10 --p-trim-left-r 10 --p-trunc-len-f 270 --p-trunc-len-r 220 --o-table count_table.qza --o-representative-sequences representative_seq.qza --o-denoising-stats denoising_stats.qza --p-n-threads 16

qiime tools export --input-path denoising_stats.qza --output-path .

qiime feature-classifier classify-consensus-vsearch --i-query representative_seq.qza --i-reference-reads /Documents/Humalite_Microbiome/database/silva-138-99-seq.qza --i-reference-taxonomy /Documents/Humalite_Microbiome/database/silva-138-99-taxonomy.qza --o-classification taxonomy.qza --p-threads 16
 
qiime taxa collapse --i-table count_table.qza --i-taxonomy taxonomy.qza --p-level 7 --o-collapsed-table asv_count.qza

qiime tools export --input-path asv_count.qza --output-path .

biom convert -i feature-table.biom -o asv_count.txt --to-tsv

qiime feature-table relative-frequency --i-table asv_count.qza --o-relative-frequency-table relative_abundance.qza

qiime tools export --input-path relative_abundance.qza --output-path . 

biom convert -i feature-table.biom -o relative_abundance.txt --to-tsv 

###This is my manifest file.
#!/bin/sh/		
sample-id	forward-absolute-filepath	reverse-absolute-filepath
CR1W_S103_L001	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR1W_S103_L001_R1_001.fastq.gz	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR1W_S103_L001_R2_001.fastq.gz
CR2W_S115_L001	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR2W_S115_L001_R1_001.fastq.gz	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR2W_S115_L001_R2_001.fastq.gz
CR3W_S127_L001	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR3W_S127_L001_R1_001.fastq.gz	/Documents/Humalite_Microbiome/RathorV4V5_Humalite/Wheat_Humalite/CR3W_S127_L001_R2_001.fastq.gz

**Comment by cherman2** [comment]
Hi @aayushirambia, 
This seems like a user support question. We would be happy to help you over at the qiime2 user forum. https://forum.qiime2.org/

I am going to close this issue, but please ask your question on the qiime2 forum if this issue still persists
