### ISSUE TITLE
Visualize relative table 

### ISSUE THREAD

**Issue by natchaphon602** [qiime2/qiime2#804]
I try to visualize relative table from "qiime feature-table relative-frequency" like below;
qiime feature-table summarize \
  --i-table genus_relative.qza \
  --o-visualization genus_relative.qzv \
  --m-sample-metadata-file metadata.txt

it show error;
(1/1) Invalid value for '--i-table': Expected an artifact of at least type
  FeatureTable[Frequency | PresenceAbsence]. An artifact of type
  FeatureTable[RelativeFrequency] was provided.

Can you describe what happen?

**Comment by lizgehret** [comment]
Hi @natchaphon602,

Thanks for reaching out! Please submit this as a 'Technical Support' question on our [User Forum](https://forum.qiime2.org/). This is where we provide user assistance and troubleshooting for QIIME 2 plugins and usage. Thanks!
