### ISSUE TITLE
Typing issue with `Plugin` attributes

### ISSUE THREAD

**Issue by colinvwood** [qiime2/qiime2#809]
The `methods`, `visualizers`, and `pipelines` class attributes of the `Plugin` class are typed as classes ([here](https://github.com/qiime2/qiime2/blob/ab00603cdf39be5866ad58463492984b699d76a9/qiime2/plugin/plugin.py#L104)) but the methods called on these class attributes (e.g. `register_function`) are instance methods, and the attributes themselves are instances when used in `plugin_setup.py` files. Thus e.g. `Type['PluginMethods']` should probably just be typed as 'PluginMethods'.

**Comment by ebolyen** [comment]
I think this was the end result of an awful lot of fighting with Sphinx. 

You're right that they are ultimately instance methods.

It also doesn't look like the docs use those attributes directly anymore, so I think we can change it:
https://develop.qiime2.org/en/latest/plugins/references/api/plugin.html#action-registration

Will just want to make sure everything still looks right.
