### ISSUE TITLE
qiime2 use dead python lib

### ISSUE THREAD

**Issue by eamanu** [qiime2/qiime2#819]
Python3.13 remove a large amount of libraries, one of them is crypt that is used in `qiime2/core/tests/test_cache.py:12`

Bug originally reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1084668 

Cheers,

**Comment by lizgehret** [comment]
Hey @eamanu,

Thanks for letting us know! When we migrate to python 3.13, our integration system will trigger an error with these dead libraries and we'll be able to address it prior to releasing QIIME 2 with python 3.13.

Cheers 🦎

**Comment by mr-c** [comment]
@lizgehret Can this issue be re-opened so that we can track when this is fixed? The Debian issue tracker is setup to check the status of this issue, so it reflecting if a fix is in would be useful to us.

Thank you!
