### ISSUE TITLE
new dummy-plugins for testing

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#93]
**Improvement Description**
- plugin with no actions
- plugin with underscore in its name and in the names of actions

These will be useful for interface testing.

**Comment by jairideout** [comment]
👍, the second plugin should have names with dashes and underscores that would have broken the CLI if name mapping was incorrect/not present.

**Comment by gregcaporaso** [comment]
@colinvwood is going to add a second dummy plugin, but it won't necessarily have these properties. We'll revisit adding those properties if we need to.

**Comment by Oddant1** [comment]
@colinvwood and @gregcaporaso the relevant PR of colin's is now merged

**Comment by gregcaporaso** [comment]
Thanks @Oddant1 and @colinvwood! This is closed with merge of #712.
